### ISSUE TITLE
try to fake placeholder when no supported

### ISSUE THREAD

**Issue by hhugo** [ocsigen/eliom#11]
I don't know if you're interested in merging this hack. We use it to fake placeholder under ie9. It set the input value with the placeholder when needed.

known isssue:
This patch doesn't do anything when trying to send_the_form/get_value. so you'll send/retrieve the value of the placeholder when the input is not set.
One could check for the classname `placeholder_class_hack` to decide whether to send the empty string or the actual value. This could be done before sending a form or when using Manip.get_value (this function doesn't exist yet)

https://github.com/besport/eliom/commit/27aa578157aa1005ff1c0d17aa1222b28db2e818

**Comment by balat** [comment]
oups my patch closes #11 of repository ocsigen.org /o\
