### ISSUE TITLE
Sharedreact: Implement module R on server side.

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#147]
I'm currently using this implementation (only for div):

```ocaml
let div l = Eliom_content.Html5.C.node
          ~init:(Eliom_content.Html5.D.div
                   (FakeReactiveData.RList.value (Shared.local l)))
          {{ Eliom_content.Html5.R.div (Shared.local %l) }}
```

But:
* this blinks at startup
* More importantly: this makes impossible to use %d on such elements, which is a big problem. (btw: what about R on client side? As the element is changing I suppose we cannot keep a pointer on it?)

TODO:
* Find a way to remove the blink (probably modify Tyxml_js.update_children?)
* Implement R. Probably by changing Tyxml's functor to take as parameter "attrib" functions, in order to be able to use shared functions)

**Comment by vasilisp** [comment]
There is an `R` module on server-side now, with the blinking mostly gone, and `%d` generally working. Closing. Report specific issues as needed.
