### ISSUE TITLE
Reason: dllsll_threads_stubs.so: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by fxfactorial** [ocsigen/eliom#169]
Having a hard time getting the target run.byte to work.

Example of my issue/setup: http://pastebin.com/ax0ewEhN

So I definitely have the correct .so(s) installed, but ocsigen is having a hard time getting to the objects. I have also tried this with opam installed in it's default, $HOME/.opam and that didn't work either, same issues. 

I also set LD_LIBRARY_PATH as the readme suggested in addition to CAML_LD_LIBRARY_PATH. 

So right now I'm adding @echos in the Makefile....not fun.

This is on ArchLinux with opam using 4.02.1 and not system compiler.

EDIT: I think I have limited the scope of the problem to a target mistake in the Makefile, most likely, as I can do `make install.opt make run.opt` without issues.

**Comment by Drup** [comment]
This is quite surprising. Not sure what the issue is. Did you check permissions and the likes ? I'm quite convinced it's a setup issue.

**Comment by fxfactorial** [comment]
It was a setup issue, thanks.
