### ISSUE TITLE
eliom depends on wikidoc

### ISSUE THREAD

**Issue by agarwal** [ocsigen/eliom#176]
I have eliom pinned to the git repo. When doing `opam install eliom`, I'm currently getting:

```
# + ocamlfind ocamlopt -c -thread -ppopt src/syntax/pa_include.cmo -syntax camlp4o -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax' -ppopt -sig-inc -ppopt ../src/lib -package 'deriving.syntax.std, js_of_ocaml.deriving.syntax,lwt.syntax' -package js_of_ocaml.syntax -package react,js_of_ocaml -package lwt,ocsigenserver,ocsigenserver.ext,tyxml.functor -w +A-4-6-7-9-27-32-33-34-37-44 -I src/lib -I src/lib/server -o src/lib/server/eliommod_services.cmx src/lib/server/eliommod_services.ml
# File "src/lib/server/eliommod_services.ml", line 437, characters 62-64:
# Error: This expression has type Ocsigen_extensions.request
#        but an expression was expected of type
#          Ocsigen_extensions.Ocsigen_request_info.request_info -> Neturl.url
# Command exited with code 2.
### stderr ###
# ocamlfind: Package `wikidoc' not found
# make: *** [all] Error 10
```

I'm assuming eliom isn't supposed to depend on wikidoc, but perhaps optionally. In either case, it should be mentioned in the `opam` file.

**Comment by Drup** [comment]
eliom doesn't depend on wikidoc, it's only optional and the message can be safely ignored (we should fix this, but nobody cared enough ...). wikidoc is not even opamized (and is nowhere near the state of quality to be).

The type error should be fixed now, Do you confirm ?

I wonder why jenkins didn't caught that ...

**Comment by agarwal** [comment]
Its working now. Thanks. (Though I don't see a commit so I don't know how.)

**Comment by Drup** [comment]
The last commit on eliom is the fix : https://github.com/ocsigen/eliom/commit/c4fabfd6bbb92a9693920fde381dc4cc6390b24e

**Comment by agarwal** [comment]
Maybe you just pushed that commit now. Otherwise, I don't know why I wouldn't have had it in the first place.

**Comment by Drup** [comment]
Ah, yes, I just pushed it. ;)

**Comment by agarwal** [comment]
Got it. Ok, thanks.
