### ISSUE TITLE
Broken demo for reactive DOM

### ISSUE THREAD

**Issue by antoine1fr** [ocsigen/eliom#178]
I don't know if its the right place to report issues about the documentation.

The [demo for reactive DOM][1] seems to be broken. Sadly, I failed to figure out how to make it work again. I'm a little lost in all the typing wizardry. :(

I'm using eliom 4.1.0.

[1]: https://ocsigen.org/eliom/4.1/manual/clientserver-html#reactive

**Comment by Drup** [comment]
Is this one broken too ?  https://ocsigen.org/eliom/dev/manual/clientserver-html

**Comment by antoine1fr** [comment]
Thanks it's perfect !

**Comment by Drup** [comment]
No problem. The issue should go on the next release.
