### ISSUE TITLE
Experimenting with eliom in the REPL

### ISSUE THREAD

**Issue by antoine1fr** [ocsigen/eliom#179]
What should I `#require` in order to experiment with eliom's server API in utop?

**Comment by antoine1fr** [comment]
I mostly want to experiment with Eliom_content.Html5.D.

**Comment by Drup** [comment]
You can't use eliom server in the REPL in general *however*, you can play with html combinators quit easily by loading tyxml.
```
# #require "tyxml" ;;
# Html5.M.(div [pcdata "patapon"]) ;;
- : [> Html5_types.div ] Html5.M.elt = <abstr>
```

If you want something more visual, you can try http://andrewray.github.io/iocamljs/tyxml.html

**Comment by antoine1fr** [comment]
Thanks it seems perfect !
