### ISSUE TITLE
Eliom_parameter.sum is broken on Eliom 4.1

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/eliom#182]
It seems that `Eliom_parameter.sum` does not work with Eliom 4.1 (the server returns a 500 error and always complains about wrong parameters). I don't know exactly when this regression was introduced, but IIRC this feature worked fine on Eliom 3.  Here is a minimal example that illustrates the problem:

```ocaml
open Eliom_content.Html5.F
open Eliom_parameter

let coucou_handler sum () =
    let msg = match sum with Inj1 s -> s | Inj2 i -> string_of_int i in
    Lwt.return
        (html
            (head (title (pcdata "Coucou")) [])
            (body [p [pcdata "You sent: "; pcdata msg]]))

let coucou_service =
    Eliom_registration.Html5.register_service
        ~path:["coucou"]
        ~get_params:Eliom_parameter.(sum (string "s") (int "i"))
        coucou_handler

let main_handler () () =
    Lwt.return
        (html
            (head (title (pcdata "Main")) [])
            (body
                [
                h1 [pcdata "Links for coucou:"];
                p [a coucou_service [pcdata "Inj1 (string)"] (Inj1 "testing")];
                p [a coucou_service [pcdata "Inj2 (int)"] (Inj2 123)];
                ]))

let main_service =
    Eliom_registration.Html5.register_service
        ~path:[]
        ~get_params:Eliom_parameter.unit
        main_handler
```

**Comment by Drup** [comment]
I can reproduce, but I really don't know what's going on.

**Comment by darioteixeira** [comment]
PR #114 seems to be the most recent modification to the code that parses sum parameters.  Perhaps @hhugo or @balat know what's going on?

**Comment by hhugo** [comment]
looking quickly at the code, I wonder if 
https://github.com/ocsigen/eliom/blob/930fdbc9b9e64b0ccc49b85a9de49e6a58d997e7/src/lib/eliom_parameter.server.ml#L263  should go inside the try-with

**Comment by vasilisp** [comment]
I tested @hhugo's hypothesis, and it seems to fix the issue. `List.assoc_remove` throws `Not_found` for one of the two cases, and we do not produce `Errors_` (as should be the case), but rather the exception bubbles up.

**Comment by vbmithr** [comment]
@drup @balat Once this is fixed, we will release a new eliom version.

**Comment by balat** [comment]
@hhugo Do you remember why you did this? 930fdbc9b9e64b0ccc49b85a9de49e6a58d997e7

**Comment by balat** [comment]
Ok I found. It's related to #45
