### ISSUE TITLE
merge sharedreact into master

### ISSUE THREAD

**Issue by vbmithr** [ocsigen/eliom#184]
And do it before it diverges more, unless you want to have extra work later.

**Comment by Drup** [comment]
But do a release before.

**Comment by vbmithr** [comment]
On 21/07/2015 15:34, Gabriel Radanne wrote:
> But do a release before.

The branch master should be released, you mean ?

**Comment by Drup** [comment]
Yes.

**Comment by vasilisp** [comment]
I did the merge. I hope everything works. `sharedreact` will stay for a few days to ease transitions, but you shouldn't commit anything there. I created a branch `4x`, which is equivalent to the old master, and meant for critical fixes that we may want to release as a new 4.x version.
