### ISSUE TITLE
 Failure("Deriving.Json: Line 1, byte 2:\nUnexpected constructor 0 for Json_stuff")

### ISSUE THREAD

**Issue by unhammer** [ocsigen/eliom#190]
I had an Eliom server written a year ago that had something like

    type thing=string list deriving (Json) 
    let thing_json = Json.t<thing>

    type stuff=A|B deriving (Json) 
    let stuff_json = Json.t<stuff>

       Eliom_registration.Ocaml.register_post_coservice'
         ~post_params:Eliom_parameter.(ocaml "param" thing_json
                                       **
                                       ocaml "param" stuff_json)
         (fun () (thing,stuff) -> proc thing)

which worked fine. But when I tried it again after an opam upgrade, the client didn't receive anything (got a 500 code), and I had to start ocsigenserver.opt with the `-v` option to get a hint as to the problem:

    ocsigenserver.opt: ocsigen:main: Exn during page generation (sending 500): Failure("Deriving.Json: Line 1, byte 2:\nUnexpected constructor 0 for Json_stuff")

https://gist.github.com/unhammer/d591195e1606cb2b2220 is a full example – note that sending ([],A) works, while sending (["something"],A) fails.

The solution was simple, just create a deriving json-type for the tuple and use that as the single ocaml param, but I feel like this should be noted in the changelog since it's a breaking change. 

Also, it'd be nice if it were reported on build. Unless it's an actual regression?

**Comment by vasilisp** [comment]
It works if you have distinct names (e.g., "param1" and "param2") for the parameters. The names are important because they correspond to HTTP parameter names. We can add a uniqueness check to provide more informative error messages.

**Comment by unhammer** [comment]
Aha, I didn't know before what the point of the names was, thanks for clearing that up. Uniqueness check sounds like it would've made debugging this easier, yes.
