### ISSUE TITLE
Mobile apps with Eliom: make possible to use toplevel injections?

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#195]
We'd like to be able to transform a responsive client-server Eliom app into an HTML5 mobile Cordova app with minimal changes to the code.
We already have:
 - the ability to register client-side functions on services, through Eliom_app.set_client_fun
 - the ability to connect the app to a default server, using Eliom_client.init_client_app

The process is initiated client-side. We provide a index.html file and the js. It must be usable without internet connection (using data in persistant cscache for example).

Now the main difficulty we have in with injections.

When injections are in client sections and refer to data in the surrounding shared section, it works, because the shared section is executed client-side.

Now how to make injections refering to server side toplevel data work? This happens mainly for:
 - services
 - remote function calls (server functions)

One possibility we are exploring is to generate the __eliom_request_data once and for (but how?) and put it in the index.html

The alternative and (imperfect) solutions currently used are:
 - Put service definitions in shared sections
 - Use services instead of server function (but this is verbose and kills the feature ...)
 - We are experimenting a possibility to define server_functions in shared sections. But this would work only for named server functions (and also this would make possible to define server function in client sections too, which is weird).

**Comment by balat** [comment]
Update: I tried to get dynamically __eliom_request_data from server when first starting the app. But I don't know how to do that. This should block the client-side program until the data is available ...

**Comment by balat** [comment]
We decided to try to write a small client side program that will:
 - call a service to get global request data when first starting the application
 - store it in local storage
 - load the main program, that will get request data from the local storage, if not present in the page.

**Comment by vasilisp** [comment]
The `srv-data` branch implements this.

We register a service that provides the global data. The location is specified by the `data_service_path` field of the `Eliom_registration.App` functor.

I use the following client program to call the above service, and store the data in `localStorage`:

```ocaml
let url =
  if Js.Unsafe.global##.___eliom_server_ = Js.undefined then
    "127.0.0.1:8080/data"
  else
    Js.to_string (Js.Unsafe.global##.___eliom_server_) ^ "/data"

let storage () =
  Js.Optdef.case (Dom_html.window##.localStorage)
    (fun () -> failwith "Browser storage not supported")
    (fun v -> v)

let get_data () =
  let%lwt {XmlHttpRequest.content} = XmlHttpRequest.get url in
  (storage ())##setItem
    (Js.string "__global_data")
    (Js.string content);
  Lwt.return ()

let _ = Lwt.async get_data
```

`init_client_app` has been modified to read our `localStorage` field and unwrap it. Thanks to the magic of `Eliom_unwrap`, the global injections are registered without much work.
