### ISSUE TITLE
shared expressions inside shared expressions

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#196]
It makes sense to allow shared expressions inside shared expressions. See the example below.
Would it be easy to allow that?

```ocaml
{shared{
  let mk_selected i =  
    Eliom_shared.React.S.map {shared#{ fun sel -> if ... then ["selected"] else [] }} selected_signal
  in
  Eliom_shared.React.S.map {shared#{
    fun v -> D.div ~a:[R.a_class (%mk_selected i)] [...]
  }}
  signal
}}
```

**Comment by vasilisp** [comment]
I wouldn't call it easy, but maybe it is doable :).

One issue that immediately comes up is that we get unbounded levels of nesting (shared expression inside shared expression inside ...). This is not the case currently, so we need to implement a stack of contexts.

Also, we have to duplicate (or intelligently share) client closures arising from what is textually the same code. We need to think what happens with side effects, with injections referring to different things, etc. (There is already duplication for client expressions appearing in shared expressions, but the problem becomes even more apparent now.)

**Comment by balat** [comment]
Actually the code I wrote does not work. It produce a runtime error "cannot wrap functional values" when called from server side.
I'm still looking for a workaround.

**Comment by vasilisp** [comment]
On the server, your `mk_class` is a function: there is a `fun sel ->` outside the `shared` section. So `mk_class` cannot be injected.

To be honest, I do not understand what you are trying to achieve :). Assuming `mk_selected` and `mk_class` are meant for the same thing, `v` would have to be a shared signal (since it is passed to `mk_class`), but then you apply `Eliom_shared.React.S.map {shared#{ fun v -> ... }} signal`, so `signal` would need to be of type `bool Eliom_shared.React.S.t Eliom_shared.React.S.t`, and I doubt that's what you want. Are `v` and `signal` meant for different things?

**Comment by balat** [comment]
Yes sorry mk_class and mk_selected are the same. I did not simplify the code correctly. I fixed the code (hopefully) above on github.

The code does not work from server side and it's normal.
But how to make it work? Is it possible to do that with the current implementation?
It's not very urgent in my case (I changed the reactive class into a effectful signal changing classes)
but I found not easy solution.

Basically I have a signal called signal (a list of items in my case).
Everytime it changes I want to update the page (display the list).
And inside this part, I want a reactive class (depending on another signal indicating which item is selected and the item number).

This would give something like:
```
Eliom_shared.React.S.map {shared#{
    fun l -> 
... 
D.li ~a:[R.a_class (Eliom_shared.React.S.map {shared#{ fun sel -> ... }} %selected_signal)] [...])
...
  }}
  signal
```

**Comment by vasilisp** [comment]
I would rewrite your original example as follows:

```ocaml
{shared{
let s, f = Eliom_shared.React.S.create true

let signal, _ = Eliom_shared.React.S.create 0

let y = 0

let mk_selected x =
  Eliom_shared.React.S.map
    {shared#{ fun b -> if b && %x > 0 then ["selected"] else [] }}
    s
}} ;;

{shared{
let mk_node signal =
  Eliom_shared.React.S.map
    {shared#{ fun v -> D.div ~a:[R.a_class (mk_selected y)] [] }}
    signal
}} ;;
```

I basically put `mk_selected` in a separate shared section so that the identifier `mk_selected` will be bound inside the shared expression. It is surely more tedious than we would want it to be, but I hope it solves the issue.

**Comment by balat** [comment]
Yes indeed. I suppose it is a solution. In my case mk_select is a local function but it could be possible to do that (with many parameters). Anyway, we have a reflexion to make ;)
