### ISSUE TITLE
Use Raw forms by default?

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#199]
By default Eliom is not using tyxml interface for forms but the interface compatible with the service identification mechanism (Eliom_parameters and so on).

But:
 - it makes difficult to understand the API doc (we don't understand why it is not like in tyxml)
 - Client server apps do not use this interface, forcing to use Raw module for each form element.

I think it would be cleaner to keep the usual tyxml interface by default, and open a module for Eliom_parameter-like form elements.

But it will break existing code :/
What do you think?

**Comment by Drup** [comment]
I agree with the issue. It becomes especially annoying when you want to have some javascript treatment (like validating a field) before sending it.

I think it would be a good occasion to rework the form interface in general to be more flexible. Propose the interface into a new module/package `Eliom_form`, ask people to migrate, then remove the special things a version later, or something like that.

**Comment by vasilisp** [comment]
It seems inconsistent to me that the `D` and `F` modules don't respect the standard TyXML signatures. In fact, I am not happy with the very existence of the `Raw` modules :). So in principle I agree with the change.

**Comment by vasilisp** [comment]
In fact, the separate module that @Drup proposes sort-of exists. `Eliom_registration_base` has all the form stuff, and little connection to `Eliom_registration`. So we can fairly easily clean-up the namespace (and `ocamldoc` output, etc.) by renaming `Eliom_registration_base` and making it public. Thoughts?

Should that change be in the release? It doesn't seem to be a lot of work.

**Comment by Drup** [comment]
`_base` also doesn't have overloaded `a` (and various other things, iirc).

**Comment by vasilisp** [comment]
Closed by #215.
