### ISSUE TITLE
PGOCaml syntax does not compile

### ISSUE THREAD

**Issue by cyocum** [ocsigen/eliom#20]
When compiling using eliomc/eliomopt with pgocaml.syntax it produces the following error:

Camlp4: Uncaught exception: DynLoader.Error ("/home/cyocum/.opam/system/lib/pgocaml/pa_pgsql.cma", "error while linking /home/cyocum/.opam/system/lib/pgocaml/pa_pgsql.cma.\nReference to undefined global `Batteries'")

I have the following installed in opam:
batteries                     2.1.0  Community-maintained foundation library
eliom                         3.0.3  Framework for programming web sites and client/server web applications
pgocaml                       1.7.1  Interface to PostgreSQL databases

I also downgraded to batteries 2.0.0 and I still get the same error.

**Comment by ZhengxunWu** [comment]
> I'm usually using server only .ml files for database interaction and I don't see this problem (using the default makefile). Using pgocaml's syntax in .eliom files may cause problems with the syntax extension indeed. But your error message seems to speak about a missing dependency on batteries in pgocaml's meta ...
> 
> If you find a fix or a workaround we would be happy to integrate it.

Hi, I use .ml fiel for database interaction but cannot compile due to syntax error. could you give me some details about how you compile it and identify the syntax? i will really really appreciate your help..thank you in advance this problem really give me headache

**Comment by balat** [comment]
We strongly recommend to use PPX syntax for PGOCaml.
Some examples can be found in Ocsigen Start's template.

For example:
https://github.com/ocsigen/ocsigen-start/blob/master/template.distillery/demo_pgocaml_db.ml
