### ISSUE TITLE
Deprecate pa_include and remove the sigs directory

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#200]
Apologies if this has been discussed before.

I wonder whether we really need `pa_include` and the `sigs` directory. We can define signatures and use standard features of the module language to include them. Am I missing something?

`sigs` is not even properly integrated into the build system.

Now (during the transition to PPX) is the right time to do it. We will be better off without a `ppx_include` preprocessor. Objections?

**Comment by vasilisp** [comment]
I just realized that `ppx_deriving` already exists, but still, do we need to use it?

**Comment by Drup** [comment]
The reason `pa_include` exists is because some substitution are not authorized in OCaml signatures, in particular when type arity doesn't match. We removed some of them over the year, so maybe it's okay to clean up that mess now. 

At least we can remove as many usages as possible.

**Comment by vasilisp** [comment]
Progress by #293.
