### ISSUE TITLE
Using OCaml libraries with Eliom?

### ISSUE THREAD

**Issue by chrismamo1** [ocsigen/eliom#205]
Right now I have a module `util.ml` which I would like to be able to use in my Eliom server-side project. I tried adding `*.ml` to the `SERVER_FILES` variable in `Makefile.options`, but since Eliom uses Camlp4 and `util.ml` uses several ppx extensions, this doesn't work.

There doesn't seem to be any kind of accessible way to use libraries requiring ppx in Eliom projects. Is this a problem with Eliom, or is there something that I'm missing?

**Comment by vasilisp** [comment]
It is a build system issue, not something more fundamental about Eliom.

The makefile uses Eliom wrappers around the standard OCaml tools (`eliomdep`, `eliomc`, etc.). Unfortunately, these rely on Camlp4 (in their standard configurations, at least). The makefile makes things simple for the standard use case, but it is not all that flexible.

One option is to hack the makefile with custom targets for your non-Eliom files. The other (and probably cleaner) option is to wrap your `util.ml` as an OCamlfind package, and then you just have to add it to `SERVER_PACKAGES`.

**Comment by Drup** [comment]
Option 1bis, Use the [ocamlbuild plugin](http://ocsigen.org/eliom/4.2/manual/workflow-compilation#h5o-3) to avoid the makefiles. There is a (rather elaborate) example [here](https://github.com/Cumulus/Cumulus).

**Comment by Drup** [comment]
Closing. Please reopen if you have further questions.
