### ISSUE TITLE
Problem with parameter type "list of files"

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/eliom#207]
I've encountered a problem with a service that takes as parameter a list of files (see self-contained code below). At runtime, the submission of the form always results in the 2nd step being skipped, and an error message to be logged: `eliom:parameter: Eliom_Wrong_parameter: files non-empty (ERROR): l.files[2], l.files[1], l.files[0]`

Though obviously I don't discount the possibility that I'm doing something stupid, note that a similar example using a **set** of files works fine, and other examples using lists of other types (ints, strings, etc) also work fine.  It seems the problem only occurs with lists of files.

I'm running the latest stable Eliom (4.2) via OPAM on OCaml 4.02.3.

```ocaml
open Eliom_content.Html5.F

let step1_service = Eliom_service.Http.service
    ~path:[""]
    ~get_params:Eliom_parameter.unit
    ()

let rec step1_handler () () =
    let step2_service = Eliom_registration.Html5.register_post_coservice
        ~scope:Eliom_common.default_session_scope
        ~fallback:step1_service
        ~post_params:Eliom_parameter.(list "l" (file "file"))
        step2_handler in
    let step2_form e_l =
        let builder name alias accum =
            let lbl = "e_file_" ^ alias in
            let hd = div
                [
                label ~a:[Raw.a_for lbl] [pcdata (Printf.sprintf "Specify file for alias '%s':" alias)];
                file_input ~a:[a_id lbl] ~name ();
                ] in
            hd :: accum in
        Eliom_parameter.(e_l.it) builder ["one"; "two"; "three"] [button ~button_type:`Submit [pcdata "Submit"]] in
    Lwt.return
        (html
        (head (title (pcdata "Hello")) [])
        (body [post_form step2_service step2_form ()]))

and step2_handler () files =
    let print file =
        p [pcdata (Printf.sprintf "File %s has size %Ld" (Eliom_request_info.get_tmp_filename file) (Eliom_request_info.get_filesize file))] in
    Lwt.return
        (html
        (head (title (pcdata "Hello")) [])
        (body (List.map print files)))

let () =
    Eliom_registration.Html5.register step1_service step1_handler
```

**Comment by vasilisp** [comment]
I can't see anything wrong with your code. I get 403's with both 4.2 and master. I will investigate.

**Comment by vasilisp** [comment]
@darioteixeira : I think the issue is now fixed in master.

@balat @vouillon @drup, this code causes issues all the time, and I find it very hard to read. I would say it requires a thorough cleanup quite urgently :).

**Comment by Drup** [comment]
@vasilisp And it was rewritten not a long time ago ...
