### ISSUE TITLE
Not_found in https://ocsigen.org/eliom/2.0/api/client/Eliom_content.Html5.D

### ISSUE THREAD

**Issue by pwbs** [ocsigen/eliom#208]
![screen shot 2015-11-02 at 15 53 06](https://cloud.githubusercontent.com/assets/15014298/10884718/d8e93756-8179-11e5-81b1-48417d02cd3e.png)
https://ocsigen.org/eliom/2.0/api/client/Eliom_content.Html5.D

**Comment by vasilisp** [comment]
You are looking at the documentation for Eliom version 2.0, which is quite old. Pick "latest stable" or "development" from the drop-down menu, and the document is there.

**Comment by pwbs** [comment]
ok, thanks, I didn't notice that drop down list.

That being said, it's still a little weird to have this "Not_found"
