### ISSUE TITLE
Bug in Eliom_shared.ReactiveData.RList?

### ISSUE THREAD

**Issue by vouillon** [ocsigen/eliom#213]
I would expect the following piece of code to output `FOO` on the console client-side, but it does not ouput anything.
```ocaml
{shared{ let log s = prerr_endline s; Lwt.return () }}
let l = Eliom_shared.ReactiveData.RList.make []
let _ =
  Eliom_shared.ReactiveData.RList.Lwt.map_p
    (Eliom_lib.create_shared_value log {{log}}) (fst l)
{client{
let _ = ReactiveData.RList.append "FOO" (snd %l)
}}
```
This [patch](https://github.com/ocsigen/eliom/files/36478/p.txt) makes it work.

There seems to be the same kind of issue in ```Eliom_shared.React.S.Lwt```.

**Comment by vasilisp** [comment]
Sorry about that. It looks like a blind transformation when implementing the `synced

**Comment by vasilisp** [comment]
I think it is fixed now.

For the record, when we construct shared values out of different client-side and server-side representations, it is easy to mistakenly inject the server-side representation (like I did here) with unpredictable results. So extra care is needed.

**Comment by vouillon** [comment]
Great. Thanks!
