### ISSUE TITLE
Incorrect type definition of services

### ISSUE THREAD

**Issue by vouillon** [ocsigen/eliom#223]
In the type declaration:
```
type ('get,'post,+'meth,+'attached,+'kind,+'tipo,'getnames,'postnames,+'registr,+'return) service
```
the variance of the last parameter is wrong.
Indeed, if the service is defined in two step as below, the parameter remains polymorphic in the type of the service `service` instead of being refined by the type of `f`.
```
let service =
  Eliom_service.Ocaml.post_coservice'
    ~name:"service"
    ~post_params:(Eliom_parameter.file "f")
    ()
let () = Eliom_registration.Ocaml.register ~service f
```
We need to check that we do not break anything by removing the variance annotation, though.

**Comment by vasilisp** [comment]
I pushed `service_variance` branches for Eliom and EBA, and their combination builds.

**Comment by vasilisp** [comment]
I think this will be fixed in the process of cleaning up the service APIs. The complicated type parameters get in the way of providing a more uniform interface (#209).

Additionally, the last parameter is what necessitates `sigs/eliom_service.mli`, which we need to get rid of in preparation for a PPX future (#200) :).

**Comment by vasilisp** [comment]
In a related note, does anyone know/remember why the last parameter of a fallback service can differ from the last parameter of the service produced (e.g., [in `Eliom_service.Http`](https://github.com/ocsigen/eliom/blob/master/src/lib/eliom_service.server.mli#L177))? Eliminating the distinction will help.

**Comment by vasilisp** [comment]
The types have changed, and there aren't variance annotations any more :).
