### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by pwbs** [ocsigen/eliom#227]
It's pretty annoying that some builds fail in Jenkins lately, as we receive many emails with that...

```
...

+ opam install --deps-only eliom
 [33m[WARNING] [m Running as root is not recommended

 [36m=-=- [m  [01mSynchronising pinned packages [m  [36m=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [m

 [KProcessing  1/1: [ [32meliom [m: local]
 [K[ [32meliom [m] /usr/src/workspace/ already up-to-date
The following dependencies couldn't be met:
  - eliom [33m ->  [mjs_of_ocaml >= dev
  - eliom [33m ->  [mppx_deriving
Your request can't be satisfied:
  - js_of_ocaml.dev is in conflict with ppx_deriving.0.1
  - js_of_ocaml.dev is in conflict with ppx_deriving.0.2
  - js_of_ocaml.dev is in conflict with ppx_deriving.0.3
  - js_of_ocaml.dev is in conflict with ppx_deriving.1.0
  - js_of_ocaml.dev is in conflict with ppx_deriving.1.1

No solution found, exiting
Build step 'Execute shell' marked build as failure
Setting commit status on GitHub for https://github.com/ocsigen/eliom/commit/586544a4ed5b756438f67507adc5a9feed6097e5
```

see also https://github.com/ocsigen/eliom-widgets/issues/12

**Comment by Drup** [comment]
I'm aware, jenkins' initialization was failing, it should be fixed now for most packages, exception being of widgets/eba.

**Comment by vasilisp** [comment]
Sorry for the noise. The specific issue with `ppx_deriving` should have gone away.

@Drup, EBA just built on 4.01, but we get a failure that I don't understand for 4.02 (missing Camlp4 while building the `text` package).

I will look into `ocsigen-widgets` (the Eliom fix may have fixed that also).

**Comment by Drup** [comment]
I think we can close this one, and keep the other open for now.

**Comment by pwbs** [comment]
Ok, thank you for looking into it. 

Just in case, note that we're having the same problem with ocsigen-widgets...
