### ISSUE TITLE
Testsuite partially broken

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#232]
The testsuite is partially broken due to client values and injections that are not linked on the client (`eliom_testsuite4.ml`, `eliom_testsuite5.ml`). As a result, some of the client-centric tests do not work (e.g., the "Client dom react" one).

It seems to be [an old issue](http://pastebin.com/nNsKKHcq) which still needs to be investigated. I will investigate, but any intuition is welcome :).

**Comment by vasilisp** [comment]
I found the commit responsible for the testsuite breakage: 9260daad497dbf85ad13281c85bc5449e439f89a . @vouillon , any insights?

**Comment by vasilisp** [comment]
The part that breaks is similar to the following program.

```ocaml
module Dbg_app =
  Eliom_registration.App (
    struct
      let application_name = "dbg"
    end)

type 'a for_unwrap = 'a * Eliom_wrap.unwrapper

[%%client type 'a for_unwrap = 'a ]

let unwrap_id = 1001

let late_unwrap_unwrapper =
  Eliom_wrap.create_unwrapper (Eliom_wrap.id_of_int unwrap_id)

let late_unwrap_value : string for_unwrap = "one", late_unwrap_unwrapper

let%client () =
  Eliom_unwrap.register_unwrapper
    (Eliom_unwrap.id_of_int ~%unwrap_id)
    (fun (v, _) -> v)

let%client () =
  ignore (Printf.sprintf "%s" ~%late_unwrap_value)

let _ =
  Dbg_app.register_service
    ~path:["foo"]
    ~get_params:Eliom_parameter.unit
    (fun () () ->
       let _ = [%client (Eliom_lib.alert "You can't see me" : unit)] in
       Lwt.return @@
       let open Eliom_content.Html5.F in html
         (Eliom_tools.F.head ~title:"foo" ())
         (body [div [pcdata "Hi"]]))
```

I am not sure whether it supposed to work. Studying the wrap/unwrap code to find out.

**Comment by vouillon** [comment]
Indeed, I think I mostly broke `Eliom_unwrap.register_unwrapper`.
Now, late unwrapping is only supported for client values, so this function will work only if called very early during client side initialization (before the values sent by the server are unmarshalled).

**Comment by vasilisp** [comment]
Thanks for taking a look! I think we can disable the offending tests and hide `register_unwrapper`.
