### ISSUE TITLE
Release Eliom 5 

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#240]
Summary of remaining tasks before release:
- [x] Reorganize & update tutorials
- [x] Switch tutorials to PPX syntax
- [x] Switch Eliom manual to PPX syntax (keep a short explanation of camlp4 syntax)
- [x] Switch Js_of_ocaml manual to PPX syntax
- [x] Release js_of_ocaml
- [ ] Pull request camlp4toppx
- [ ] Very short intro page of tyxml manual (the basics) https://github.com/ocsigen/tyxml/blob/master/doc/manual-wiki/intro.wiki

Please check boxes and add a comment when done :)

**Comment by balat** [comment]
Finished reorganizing tutorials. It's now much easier to find his way into the doc. I hope ...

**Comment by Drup** [comment]
- [x] release reactiveData

**Comment by vasilisp** [comment]
I am not sure we can realistically get all the Ocsigen plugins into the upstream Camlp4-to-PPX (with all our plugins enabled by default) before the Eliom release. There are issues to be investigated, e.g., conflicts between the new plugins and the old. I think we should proceed with a pointer to the fork for now.

**Comment by hhugo** [comment]
I plan to release js_of_ocaml later today

**Comment by vasilisp** [comment]
[ ] Get the testsuite working.

**Comment by Drup** [comment]
Switch Js_of_ocaml manual to PPX syntax: https://github.com/ocsigen/js_of_ocaml/pull/407

**Comment by hhugo** [comment]
js_of_ocaml 2.7 https://github.com/ocaml/opam-repository/pull/5489

**Comment by balat** [comment]
- [ ] Finish switching Eliom manual to new syntax, for example http://ocsigen.org/eliom/dev/manual/clientserver-language or http://ocsigen.org/eliom/dev/manual/clientserver-communication#h5o-24 or http://ocsigen.org/eliom/dev/manual/clientserver-html section html syntax (make clear that it is camlp4 only)
- [ ] Where is the manual page on eliom_shared?
- [ ] Migration pages: put them all at the same place (ok for Eliom's manual)

**Comment by vasilisp** [comment]
`eliomdoc` currently tries to pass `-printer o` to the Eliom PPX binaries, and things break. We need to get this right for EBA to build on Jenkins. I don't know whether this is release-critical...

**Comment by vasilisp** [comment]
Testing a fix for the above, I hope it will find its way into master today.

**Comment by vasilisp** [comment]
I put a migration page in the same place as the old ones: http://ocsigen.org/eliom/Eliom50 . It covers forms (the only truly breaking change) and also points to the PPX transition instructions.

**Comment by vasilisp** [comment]
`Eliom_shared` manual in progress, ETA Thursday, sorry for the delay :).

**Comment by vasilisp** [comment]
The manual page for `Eliom_shared` is now online: https://ocsigen.org/eliom/dev/manual/clientserver-react .

**Comment by vasilisp** [comment]
Are we ready? There are related tasks with the peripheral projects (EBA, `camlp4-to-ppx`) but I think we can release Eliom itself.

**Comment by balat** [comment]
- [ ] Go through the checklist for releases: https://ocsigen.org/devarea/releases

**Comment by balat** [comment]
The dev version of Eliom manual is still not updated on the Web site, is it normal?
(PPX syntax)

**Comment by vasilisp** [comment]
@balat, [this page](http://ocsigen.org/eliom/dev/manual/clientserver-language) stays to document Camlp4, there is documentation for [PPX also](http://ocsigen.org/eliom/dev/api/ppx/Ppx_eliom) (as API documentation). Other than that, we use Camlp4 only where necessary (HTML syntax). Have I forgotten something?

**Comment by balat** [comment]
Ok as discussed, it is strange to have the asymmetry in documentation, isn't it?
Is it  possible to move both in the manual?

**Comment by vasilisp** [comment]
Not sure. It was quite complicated to get PPX to show up like that in the API doc. I don't know how to revert this, @Drup did it :).

**Comment by balat** [comment]
Yes but moving from API to wiki should be easier, I think ...

**Comment by vasilisp** [comment]
Also: the PPX implementation doesn't have license headers. Is that crucial?

**Comment by balat** [comment]
Crucial, probably not, but it's better to add them.

**Comment by vasilisp** [comment]
I am moving the PPX doc to the manual, and I will link to it from what is now `Ppx_js` (I don't know how to hide the latter)

**Comment by balat** [comment]
Thank you :)

**Comment by Drup** [comment]
I don't plan on translating the ppx doc to wiki for a rather larger number of reason that I already explained. I tried to tweak the menu on the left, but couldn't make it work. So I just added linked everywhere it was relevant. Nothing more to do there imho.

**Comment by balat** [comment]
I think we are ready :)
For the tar.gz, I suggest we add a link to github from the download page (and keep the current packages in a section "old releases").
We should do the same for all projects ...

I'll prepare an announcement (that I will probably send on monday).

**Comment by vasilisp** [comment]
OPAM pull request: ocaml/opam-repository#5521

**Comment by vasilisp** [comment]
We are waiting to hear back about OPAM.

The website has been updated (including a 5.0 version of the tutorial).

With respect to announcements, there is a draft for the blog: ocsigen/ocsigen.github.io@91f4b2f7e3f6159c1f72e5ec63ad614b3a4ad883 .

**Comment by Drup** [comment]
@vasilisp I think you should write a little something about each feature (like, one or two lines).

**Comment by vasilisp** [comment]
@Drup it is now more verbose. Feel free to modify anything you want (it goes without saying). We should probably publish it on Monday morning.

**Comment by Drup** [comment]
@vasilisp Much nicer! I'll see if I have something to add before monday.

**Comment by balat** [comment]
- [x] Tag and release git(hub)
- [x] Release on ocsigen.org
- [ ] Announcement on caml list + ocsigen list
- [ ] Announcement on blog/planet
- [ ] Announcement on Social networks
- [ ] Announcement on ocsigen.org (main page + Eliom)
