### ISSUE TITLE
Wrong display in documentation

### ISSUE THREAD

**Issue by slegrand45** [ocsigen/eliom#242]
In page http://ocsigen.org/eliom/dev/manual/server-services#h5o-16, section "RESTful apps: PUT and DELETE services", the code example is not correctly displayed. It seems that the string ">>=" breaks the page layout: https://github.com/ocsigen/eliom/blob/master/doc/manual-wiki/server-services.wiki#L598

**Comment by vasilisp** [comment]
Thanks, fixed. The `>>` can be escaped with `~>>`.
