### ISSUE TITLE
"opam install eliom" fails, make fails... now what? osx 10.7.5

### ISSUE THREAD

**Issue by vectorselector** [ocsigen/eliom#243]
So, "opam install eliom" fails with a sqlite3 dependency. 

The following actions failed
  ∗  install sqlite3 4.0.3
No changes have been performed

=-=- sqlite3.4.0.3 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. "opam depext sqlite3.4.0.3" may help you find the correct installation for your system.

upon which I type that and then get 
 Detecting depexts using flags: x86_64 osx homebrew
 No extra OS packages requirements found

and then i check which sqlite3
/usr/local/Cellar/sqlite/3.10.2/bin/sqlite3
which is newer than the specified sqlite3.4.0.3 (strange versioning!?)
and of course, i DID go to the sqlite downloads page and nearly started crying when I tried to find old versions... never mind how to build it...

so, speaking of building, i tried to download the Eliom github source, as the second option shows and then when i typed "make" i got a partial make process and then...
ocamlfind: Package `ocsigenserver.cookies' not found
Command exited with code 2.
Compilation unsuccessful after building 69 targets (68 cached) in 00:00:00.
make: *** [all] Error 10

now I am really really frustrated and I just want to use your framework...

**Comment by vectorselector** [comment]
basically, why is there a hardcoded dependency upon a specific version of sqlite3 and is there anything I can do about it? I have a newer sqlite3  from homebrew and the one that came with the system which is OSX 10.7.5

**Comment by vasilisp** [comment]
I have neither experience with OS X nor access to Apple hardware, so my advice will be general.

Maybe you need to install a development package for Sqlite3? In many distributions (e.g., Debian/Ubuntu) the development files (headers etc.) are in separate packages than the runtime components. You may want to as for help in the [`ocaml-sqlite3` issue tracker](https://github.com/mmottl/sqlite3-ocaml/issues).

The dependency in question is from `ocsigenserver`: `("dbm" | "sqlite3")`, with no version constraints. If you fail to get `sqlite3` working, try installing `dbm` before the Ocsigen packages.

OPAM is an excellent package manager overall. The OPAM `depext`  plugin (`opam install depext`) generally allows you to find the needed external packages easily. Unfortunately, the [package specification for `sqlite3`](https://github.com/ocaml/opam-repository/blob/master/packages/sqlite3/sqlite3.4.0.3/opam) doesn't provide external dependencies about OS X.

OPAM fulfills the need for an installer on Unix systems, including OS X. Fixing any glitches in the OPAM metadata for OS X is a much better use of time than maintaining Mac-specific installers. Of course, this relies on contributions from people who use OS X.

**Comment by vasilisp** [comment]
I don't recommend manual installation, but the message about `ocsigenserver.cookies` is presumably because you don't have `ocsigenserver` installed. The latter is a strict dependency of Eliom.

**Comment by vasilisp** [comment]
Another thing I forgot: `4.0.3` is the version of the OCaml bindings to Sqlite3 (OPAM package `sqlite3`), which is separate from the version of Sqlite3 itself. You should be fine  with Sqlite3 3.10.x .

**Comment by vectorselector** [comment]
so, forgetting the opam install eliom, which fails over the sqlite3 version number.
on the topic of building eliom:

Yes sir, you are correct! 
So, i went and cloned https://github.com/ocsigen/ocsigenserver.git
and i sh configured, made, installed... 

so NOW, i advanced past building 69 targets and now when i try to make install i get to 158 targets built and I get an error about an "Unbound module"

Error: Unbound module Ocsipersist
Command exited with code 2.
Compilation unsuccessful af

so when I try to do opam update and opam install ocsipersist like the github page says
https://github.com/ocsigen/ocsipersist
it  says

[ERROR] No package named ocsipersist found.

it's strange!?

**Comment by Drup** [comment]
Most of your complications come from not using opam. Does `opam install dbm eliom` work ?

**Comment by vectorselector** [comment]
yes, you are correct- i did the "brew install" process, per the website and only opam in the end
...
and your command suggestion `opam install dbm eliom` 
it works!!!!!!

thank you, thank you, thank you!

**Comment by Drup** [comment]
Happy to help. I'm not sure where does the issue with sqlite3 comes from (you might want to report that to [sqlite3](https://github.com/mmottl/sqlite3-ocaml/issues)), but thankfully, there is an alternative for eliom.

**Comment by vectorselector** [comment]
as vasilisp points out above, it's something involving some discrepency between the ocaml bindings, the actual paths to my sqlites more likely than the exact version...i'll look into it sometime.

thank you both for the information. it's my first ocaml experience so i am unfamiliar with opam and I still don't quite understand how  ocsipersist doesnt' exist on an updated opam, but i'll have to get more familiar with opam, as pointed out.

**Comment by vasilisp** [comment]
I know it is not important for your Eliom installation, but for completeness' sake: there is no `ocsipersist` package in the OPAM database :). If you really want to use https://github.com/ocsigen/ocsipersist , you need to use OPAM-pinning (which allows you to install stuff directly from Git and other repositories):

```shell
opam pin add ocsipersist https://github.com/ocsigen/ocsipersist.git
```

But you don't need to. A version of Ocsipersist distributed with Ocsigen Server, and it is now installed on your system. (We are planning to remove Ocsipersist from the server and use the separate package, but we are not there yet.)

**Comment by vectorselector** [comment]
ah HA! i had thought the note was in reference to git pinning
thank you

**Comment by mmottl** [comment]
@vectorselector I'm not quite sure what your problem with ``sqlite3`` may be, but maybe some of the instructions in its README could help.  In particular, please make sure that ``pkg-config`` is installed, is accessible via your ``PATH``, and provides the right compilation and linking flags for your configuration.
