### ISSUE TITLE
Shared sections and type inference

### ISSUE THREAD

**Issue by vouillon** [ocsigen/eliom#244]
This piece of code:
```
let%shared f= ~%()
```
compiled with:
```
eliomc -ppx -infer bug.eliom && js_of_eliom -ppx -c bug.eliom
```
yields the following warning:
```
File "bug.eliom", line 1, characters 16-18:
Warning 22: The type of this injected value contains a type variable that could be wrongly inferred.
```

**Comment by vasilisp** [comment]
@Drup, have you looked at this? If not, please assign it to yourself or to me :). It looks serious enough to include it in a bugfix release.

**Comment by vasilisp** [comment]
I think 4d8aa62 fixes the issue. @Drup, please take a look!
