### ISSUE TITLE
Mobile apps: Make server functions and services work with client side programs

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#245]
May be: Make possible to define server_functions and services in shared sections
and do not use ~% any more for them.

**Comment by balat** [comment]
I created a branch called mobile.

It contains a first version of client side server functions.

The client side version takes a mandatory parameter ~name, to force using named coservices (is optional on server side).

But it is not perfect:
1. server_function usually takes the function as second parameter (because it does the registration). I replace this by `unit` but it is weird. You must define the actual function on server side, and a value with the same name on client side = (). 
2. Typing can be broken. There is nothing to enforce that the return type on client side is the same as on server side.

Example:

```ocaml
let%server f = Eba_session.connected_rpc set_profile
let%client f = ()

let%shared set_profile_rpc : (_, unit) server_function =
  server_function ~name:"setprofile" [%derive.json: set_profile_t] f
```

To solve 1, we could introduce a new ppx syntax, similar to but making possible to have a different value on server on client sides [%unshared f / () ]

To solve 2, make some syntax extension add type annotation somewhere?

**Comment by vasilisp** [comment]
I think we can close this. We actually do the opposite of what we were thinking at the time (i.e., inject services and server functions).
