### ISSUE TITLE
Mobile apps: client sections invalid after rebuilding the app 

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#250]
When the server side program is recompiled, client program gets outdated.
* Be careful with interface (server_function, services): types must not change
* coservices, server_functions: a solution would be to use only named services/server functions
* Client value identifiers: Identifiers for client sections are created at compile time and included in the client side program. But if the sever side program is updated, this will fail.
This means that even if the interface has not changed, we must update the mobile app, everytime the server side is recompiled.

Three ideas:
* Keep one server running for each version of the app (be careful with database compatibility!)
* One workaround would be to update the client side program dynamically everytime we detect an incompatibility (but how to do that without interrupting what the user is currently doing?). May be detect and update in background (regular polls or comet?).
* Another solution would be to detect and forbid completely client sections (how?). That is: make sure everything is generated on client side ...

**Comment by balat** [comment]
2016-03-09: After today's discussion, we (Jerome, Vasilis, me) think that using a different version of the program on server and client is dangerous for several reasons:
 - client-server interfaces may have changed (types of server functions)
 - client values identifiers (global or local) may have changed (even if the server side program has not changed, because the number of client values may vary ...)

The only reliable solution is probably to update the client side program automatically, each time the server is restarted. For ex using:
https://github.com/nordnet/cordova-hot-code-push

**Comment by vasilisp** [comment]
Cordova Hot-Code-Push works for our purposes, and I doubt we have any plans for more "stable" interfaces, so I guess we can close this. Re-open if I am wrong :).
