### ISSUE TITLE
cannot get Eliom 5.0 working

### ISSUE THREAD

**Issue by pierregobin** [ocsigen/eliom#251]
I am using ocaml 4.02.3, on ubuntu ; all installed with opam.
I try to make simple example with eliom : `eliom-distillery -name mysite -template basic.ppx -target-directory mysite`; but then it fails to compile (make test.byte) , I got :+1: 

> eliomdep -client -ppx -package lwt.ppx -package js_of_ocaml.deriving.ppx -package  s_of_ocaml.ppx mysite.eliom > _deps/mysite.eliom.client
Fatal error: exception Fl_package_base.No_such_package("js_of_ocaml.deriving.ppx", "")
make: *** [_deps/mysite.eliom.client] Erreur 2

When I modify Makefile.options by removing all ".ppx" extension of CLIENT_PACKAGES & SERVER_PACKAGES, then it works.

**Comment by vasilisp** [comment]
The template refers to the PPX extensions that are commonly used in Eliom applications, including `js_of_ocaml.deriving.ppx`, which automatically builds functions for converting to/from JSON via the `[@@deriving.json]` syntax. `js_of_ocaml.deriving.ppx` gets built if `ppx_deriving` is present. So if you need the `js_of_ocaml.deriving.ppx` functionality, then `opam install ppx_deriving`, otherwise the solution is to remove `js_of_ocaml.deriving.ppx` from `CLIENT_PACKAGES` and `SERVER_PACKAGES`, as you did. (The other PPX packages can stay.)

**Comment by Drup** [comment]
@vasilisp Maybe we should add it as a dependency of eliom (or remove from the base template).

**Comment by pierregobin** [comment]
The point is that it is not possible, without hacking the Makefile.options, to do a simple example as explained in the tutorial : 

`eliom-distillery -name mysite -template basic.ppx -target-directory mysite`
`make test.byte`

Which was working fine with the previous version. Or do I miss sth ?

**Comment by Drup** [comment]
@pierregobin It does work, just not on your system, and I don't understand why.

**Comment by Drup** [comment]
@pierregobin could you pastebin somewhere the result of `opam list -i`, `ocamlfind list` and `opam report` ?

**Comment by pierregobin** [comment]
@Drup, attached are files for `opam list -i` , `ocamlfind list`. `opam report` is not recognized (I am using 1.3.0~dev3)

[ocamlfindlist.txt](https://github.com/ocsigen/eliom/files/118676/ocamlfindlist.txt)
[opam_list.txt](https://github.com/ocsigen/eliom/files/118677/opam_list.tx

**Comment by pierregobin** [comment]
**@Drup**, I have reinstall opam (v.1.2.2), re-init, install 4.02.3, utop & eliom. It was still not working. Then I installed deriving_ppx.3.0.0 as you already mentioned in SO, and now it is working fine. Thx !

**Comment by vasilisp** [comment]
@pierregobin sure, we must make it work out of the box. Thanks for reporting! To be fixed.

@Drup I tried to add the dependency to master (3a17bcf) before doing an `opam-repository` PR for 5.0.0. The OPAM failure in Jenkins failure is really bizarre. I can't reproduce it locally with the same pinned packages.

**Comment by Drup** [comment]
@vasilisp Solver failure maybe ? I'm not sure which solver is used on jenkins.

**Comment by vasilisp** [comment]
With some trial and error, I figured out what was wrong with Jenkins; Eliom was still using the 4.02.1 switch, which conflicts with `ppx_deriving.3.0`.

This brings up another issue: if we retain the `ppx_deriving` dependency, then we will have a non-linear (and as such confusing) OCaml dependency: either precisely `4.01.0` or `>= 4.02.2`. So it is probably better to remove `ppx_deriving` from the template and document where necessary.

**Comment by vasilisp** [comment]
c030ceb6d0f3ff181987ff94e30116f025e51c1e reverts the hard dependency on `ppx_deriving`; not supporting early 4.02.x versions would be confusing. I have removed the dependency on `js_of_ocaml.deriving.ppx` from the template, and documented the need for `ppx_deriving` in the Eliom manual and the tutorial (8b7f8a979baf313bf56236370a2d1a011265cbe8 and ocsigen/tutorial@54ff89c9650c37ff26650751f6cbb813baa899d3). I think this can be closed.
