### ISSUE TITLE
Client version of register functions to replace Eliom_content.set_client_fun

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#253]
And make possible to register in shared sections

**Comment by balat** [comment]
I just added a client side version of set_client_fun in Eliom_content (hidden in interface). It will be used to implement Eliom_registration on client side.

**Comment by vasilisp** [comment]
I will get to this once #293 gets merged (before that, maintaining another branch that touches `Eliom_registration` would be a lot of unnecessary rebasing work).

**Comment by vasilisp** [comment]
We have a version of this in the `client-registration` branch. It permits the following style of programming:

```ocaml
[%%shared
module App =
   Eliom_registration.App (struct
     let application_name = "app"
     let global_data_path = None
   end)
]

let service =
  Eliom_service.create
    ~id:(Eliom_service.Path [])
    ~meth:(Eliom_service.Get Eliom_parameter.unit)
    ()

let%shared service_handler () () =
  Lwt.return
    (Eliom_tools.F.html ~title:"foo"
       (Eliom_content.Html.(D.body [D.h1 [D.pcdata "foo"]])))

let%shared () =
  App.register ?app ~service:~%service service_handler
```

i.e., the services are defined once on the server (not mandatory, but I think it is preferable), the handlers are implemented as shared code, and the registration happens on both the server and the client.

The client-side `Eliom_registration` provides the submodules that look relevant: `Html`, `App`, and `Action` (#271).

I will do a PR once #299 gets out of the way.
