### ISSUE TITLE
__eliom_request_data and Mobile apps

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#254]
When doing a client side app, Eliom data (__eliom_request_data, etc.) cannot be sent by server.

* Workaround: do not use injection of top level values. Use services and RPCs defined in shared sections. And try to avoid others. I'll test this soon.
* May be solution: generate eliom_data statically, for ex with PPX, and include it in JS. Problem, data must be static (which is not always the case in BeSport) and how to enforce this?
* Another may be solution: Load eliom data chen launching the app for the first time. Problems:
  * will not work if not connected (but in most cases it's not a problem as we need the connection anyway)
  * Client program must wait until the data is retrieved before continuing its initialization. Is it possible to do that?

**Comment by vasilisp** [comment]
@balat, are we done with this?
