### ISSUE TITLE
ppx support in ocamlbuild_eliom

### ISSUE THREAD

**Issue by paurkedal** [ocsigen/eliom#257]
`ocamlbuild_eliom.ml` currently hardcodes the camlp4o preprocessor option and related package names. I think it could support ppx e.g. via a global ref which could be set `Before_options` without to intrusive changes.

**Comment by vasilisp** [comment]
[Sort-of working](https://github.com/ocsigen/eliom/tree/ocamlbuild-ppx). I am not very familiar with the old plugin and with Ocamlbuild in general, so I need to check it a bit more carefully. It doesn't need intrusive changes indeed.

**Comment by paurkedal** [comment]
Looks good, I'll give it a try in the evening.

**Comment by paurkedal** [comment]
I haven't converted a whole project yet, but tried a single module within a project, and added the following to the `_tags` in the appropriate subdirectory:
```
<panograph_basic_editors.*>: eliom_ppx
<client/panograph_basic_editors.*>: package(lwt.ppx), package(js_of_ocaml.ppx)
<server/panograph_basic_editors.*>: package(lwt.ppx), thread
```
The module compiled successfully along with the rest of the library, which was still camlp4.  So, I'd say it's working, and nicely done. I prefer the `eliom_ppx` tag over changing `myocamlbuild.ml'.

**Comment by paurkedal** [comment]
Tested also on a full (mini-)project: paurkedal/spreadsheet-demo@e49f90243a0c870260c8e360e4516583454625e7

**Comment by vasilisp** [comment]
Awesome, thank you for testing! I am planning to do a pull request, and I hope it will be in master in a few days. Your project looks like a cool Eliom demo, by the way :).

**Comment by paurkedal** [comment]
Great, looking forward to converting my remaining projects, though I'll probably hold that till this reaches the official opam repository.

I wrote this code to test large-scale use of FRP in Eliom, and I think it was very cool to be able to write a spreadsheet with so few lines of code.  It's almost pedagogical, maybe with some more comments, a study for the interested more than the first FPR Eliom code one would see.

Although Eliom react is a bliss compared to traditional web programming, I felt that I had to abandon extensive use of react on the client side due to the known memory management issue, and related performance issues, as leaked signals accumulated.  Have been wondering if something could be done to work around it, but that's an topic for another thread.

**Comment by vasilisp** [comment]
Are you referring to the lack of weak references in JS or to something else? For weak references, I can imagine using [WeakMap](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) when the browser permits it (and falling back to the current stub otherwise).

I encourage you to open an issue with an Eliom example that exposes memory management trouble, and we will take it from there.

**Comment by paurkedal** [comment]
Yes, the issue is the lack of weak references, and they cannot be implemented in terms of the WeakMap, which only provides weak keys.  There have been proposals, but as far as I recall there is a real security issues and there is doubt about the usefulness, both related to exposure of the non-deterministic behaviour of GC.  I'll open a separate issue.
