### ISSUE TITLE
dependencies on sqlite3 

### ISSUE THREAD

**Issue by pierregobin** [ocsigen/eliom#260]
I have to install manually sqlite3 package otherwise, I got the the error <br>

> ocsigenserver: ocsigen:main: Fatal - Findlib package ocsigenserver.ext.ocsipersist-sqlite not found:

**Comment by vasilisp** [comment]
As far as I can tell, `eliom-distillery` produces a template which uses the `Ocsipersist` backend that you have installed (DBM or Sqlite). Did you by chance run `eliom-distillery` with some installation that had Sqlite and subsequently tried to run the same project with an installation that has DBM? In such cases, you can manually specify the DB backend that you want via the `PERSISTENT_DATA_BACKEND` variable in `Makefile.options`.
