### ISSUE TITLE
Broken links on Eliom 5 migration page

### ISSUE THREAD

**Issue by pveber** [ocsigen/eliom#264]
The two first links of the [migration page](http://ocsigen.org/eliom/Eliom50) (Forms paragraph) are broken. The correct links are used a bit after that.

**Comment by vasilisp** [comment]
Thanks. Unfortunately, `ocamldoc` doesn't get along with the module system all that well. Therefore, we cannot do much better than removing the links.

**Comment by pveber** [comment]
Yes I understand. Well, no link is better than broken link. Thanks!
