### ISSUE TITLE
Missing unit form parameter.

### ISSUE THREAD

**Issue by pveber** [ocsigen/eliom#267]
I think `Eliom_content.Html5.{D,F}.Form` misses a `unit param` constructor:
```
val unit : unit param
```
It would be logical since we have `Eliom_parameter.unit`, no?

**Comment by vasilisp** [comment]
It makes sense to have a service with a `unit` argument, hence `Eliom_parameter.unit` exists. But how can a form widget be filled-in with a unit? The one widget that can be used for a side-effect is special-cased (`button_no_value`).

**Comment by pveber** [comment]
And that is exactly what I needed! Sorry I missed it in the documentation.
