### ISSUE TITLE
Implement client side actions

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#271]
By default Eliom's action services generate a page on server side.
In the case of a mobile app, the page should be generated on client side after action ...

At the moment, it is not recommended the generate pages server-side for client applications, because this would probably send client values (which does not work if the server side app has been updated).

- We should probably have two cases: either the action is performed on server side or there is a client side implementation, in which case it is just a function call (+ redraw) see #272
- *Warning:* Registering an action sets field `send_appl_content` to XAlways on server side. Should be the same on client side! (Eliom_registration.Action)

**Comment by balat** [comment]
I suggest to simplify the semantics, and to have exactly the same behaviour as for other services: actions must be implemented on client side for mobile apps, as all otehr services. If the action is supposed to do soething on the server, just call a server function.

To keep the exact same semantics, we should redisplay the page by default after the action ...

**Comment by vasilisp** [comment]
Done (#308 + #336).
