### ISSUE TITLE
Generating eliomi file with `eliomc -i` gives interface using old syntax extension instead of ppx

### ISSUE THREAD

**Issue by sagotch** [ocsigen/eliom#276]
```
File "foo.eliomi", line 2, characters 0-1:
Error: Syntax error

$ cat foo.eliomi
(* WARNING `eliomc -i' generated this pretty ad-hoc - use with care! *)
{server{ 
...
}}
{client{
}}
```

**Comment by sagotch** [comment]
Also, maybe I did a mistake, but my module is defined in a `[%%shared ]` section, while the `{client{ }}` part of my eliomi is empty.

**Comment by vasilisp** [comment]
I don't think you made a mistake. It is just that `eliomc -i` is fairly primitive, and it always prints a server section followed by a client section.
