### ISSUE TITLE
Can't install opam on debian testing : camlp4 and js_of_ocaml dependencies KO

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/eliom#283]
I had a dependency problem on my old opam installation, so I nuked my .opam in order to reinstall from scratch. But then I am stuck with :
```
opam install eliom
The following dependencies couldn't be met:
  - eliom -> camlp4 <= 4.02+6
  - eliom -> js_of_ocaml < 2.0
Your request can't be satisfied:
  - camlp4<=4.02+6 is not available because your system doesn't comply with !preinstalled & ocaml-version >= "4.02" & ocaml-version < "4.03".
  - js_of_ocaml<2.0 is not available because your system doesn't comply with ocaml-version <= "4.01.0".

No solution found, exiting
```

Soooo..... what can I do?

**Comment by vasilisp** [comment]
If I understand the `preinstalled` field correctly, the above constraint implies that you will need an OPAM-managed OCaml installation:

```shell
opam switch 4.02.3
```

**Comment by Cochonours** [comment]
You understood well!! It worked :) Maybe opam could have suggested such a solution..
