### ISSUE TITLE
Can't compile project after opam update

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/eliom#284]
When I ran `make test.byte` I got the following error : `/bin/sh: 1: eliomdep: not found`

So I ran `make clean` and then `make test.byte` again, to be stuck on another error : `make: js_of_eliom : commande introuvable`

I wanted to run `eliom-distillery` to see if a new project would compile or not but this command doesn't seem to be available anymore..?

**Comment by vasilisp** [comment]
None of the Eliom tools seems to be in your path. Assuming that Eliom is installed, you need to do

```
eval $(opam config env)
```

in your current shell to bring your environment in sync with your OPAM setup.

**Comment by Cochonours** [comment]
Oh yes, I was sure I did this, but that was probably before wiping everything out and reinstalling from scratch... Thanks
