### ISSUE TITLE
Eliom/Manip: CSS opacity and OCaml option

### ISSUE THREAD

**Issue by pwbs** [ocsigen/eliom#300]
I kind of understand why we have an option in
```ocaml
val Manip.Css.opacity : 'a Eliom_content.Html5.elt -> string option
```
but I don't see the point of having an option here.
```ocaml
val Manip.SetCss.opacity : 'a Eliom_content.Html5.elt -> string option -> unit
```
What does `Manip.SetCss.opacity e None` do? Isn't it completely useless? 
Well, it could be used for `Manip.SetCss.opacity e1 (Manip.Css.opacity e2)`...

Could we have instead this one?
```ocaml
val Manip.SetCss.opacity : 'a Eliom_content.Html5.elt -> string -> unit
```

in which case
```ocaml
      let opacity elt v =
        let elt = get_unique_elt "SetCss.opacity" elt in
        elt##style##opacity <- match v with None -> Js.undefined | Some v -> Js.def (Js.bytestring v)
```
would simply become 
```ocaml
      let opacity elt v =
        let elt = get_unique_elt "SetCss.opacity" elt in
        elt##style##opacity <- Js.def (Js.bytestring v)
```

**Comment by vasilisp** [comment]
`opacity` seems to be the only function returning/accepting an option in `Css` and `SetCss`. I doubt that opacity is the only thing that can be undefined, so we should fix the inconsistency.

**Comment by vasilisp** [comment]
In fact, the inconsistency arises in JSOO (`Dom_html.cssStyleDeclaration`), where [`opacity` is the only `optdef`](https://github.com/ocsigen/js_of_ocaml/blob/707cead7b6c3dfdd6ff113f59958b989ccdda6db/lib/dom_html.mli#L98).

**Comment by vouillon** [comment]
I guess the reason is that `opacity` was not supported by IE before version 9.

**Comment by vouillon** [comment]
I agree with @pwbs that there is no point in using an option for `Manip.SetCss.opacity`.
