### ISSUE TITLE
Client-side services: wrong session info

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#301]
* Start an app on an URL with GET parameters.
* Follow a link to an intenal (client-side generated) page wihtout GET parameters 
* Do a client side reload (call change_page to a reload_action).
→ The GET parameters reappear in the URL!

I think this is due to the fact that "si" is not updated after calling a client side service.
In ```eliom_client.client```, ```Eliom_request_info.set_session_info``` is called in ```set_content``` but not in ```local_set_content```.

@vasilisp Can you have a look at this?  Thanks :)
Tell me if you need help.

**Comment by vasilisp** [comment]
I will look into it :).

**Comment by vasilisp** [comment]
The `i301` branch has a patch for this. The specific problem seems to be fixed. However, I do not understand the `sess_info` fields very well (e.g., what is `si_other_get_params`?), and I am not very confident about the accuracy of the updated data.
