### ISSUE TITLE
reload_action broken

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#306]
Hello,

We have a problem with reload_action, in the case the previous page was generated by a service with POST parameters.
@vasilis can you check whether `reload_fun` is ok for POST services?
It should be the client function of the fallback ... (`reload_fun` is the function to be called for reloading the page, without POST parameters, as if the user were pressing reload button).

But we don't have a fallback anymore :-O

**Comment by balat** [comment]
An alternative (to be tested) could be to remove ```reload_fun``` from services, and use ```client_fun``` when there is no POST parameter, and "the previous reload function" where there are POST parameters. (??)

**Comment by vasilisp** [comment]
I also think it is broken. We use the same function given for the `client_fun`, but that one expects POST parameters. The `Obj.magic` was hidding the problem previously.

#305 only permits reload functions for services with no POST parameters.

**Comment by vasilisp** [comment]
I think the alternative is equivalent to what happens in #305. `Eliom_service.reload_fun` returns `None` for services with POST parameters, so we keep the previous value of `Eliom_client.reload_function`.

**Comment by balat** [comment]
Ok I hadn't seen #305 :)
It seems to do about what I suggested in my second comment.
I'll give a closer look to #305 tomorrow.

**Comment by vasilisp** [comment]
If that's not enough, we can provide an `Eliom_registration.X.create_post` that emulates the old `post_coservice`, accepts a fallback, and does some internal magic for using the fallback's `client_fun` for reload.

It is easy to implement. I haven't done this already because the API would become a bit uglier, and I didn't feel there was much interest in attached POST coservices :).

**Comment by vasilisp** [comment]
Closing this. Reload actions now go through service routing. Reload functions no longer get in the way.
