### ISSUE TITLE
Eliom6 introduces some redundancy in declaration of attached post co-services

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/eliom#311]
Consider the minimal example of an attached POST co-service listed at the end.  It implements a simple 2-step service which presents a form on the 1st step and displays the submitted values on the 2nd step.

The declaration of the (GET, POST) parameters for the 2nd step is `Post (Eliom_parameter.unit, Eliom_parameter.(int "n" ** string "s"))`.  However, the GET parameter declaration is redundant, because we know already it must be `Eliom_parameter.unit` from the fallback.  Note that previous versions of Eliom did not have this redundancy.

```ocaml
open Eliom_content.Html.F

let coucou_service =
    Eliom_service.create
        ~meth:(Get Eliom_parameter.unit)
        ~id:(Path [])
        ()

let coucou_handler () () =
    let rec step1_handler () () =
        let step2_service =
            Eliom_registration.Html.create
                ~scope:Eliom_common.default_session_scope
                ~meth:(Post (Eliom_parameter.unit, Eliom_parameter.(int "n" ** string "s")))
                ~id:(Fallback coucou_service)
                step2_handler in
        let step2_form (n, s) =
            [
            Form.input ~input_type:`Text ~name:n ~value:0 Form.int;
            Form.input ~input_type:`Text ~name:s ~value:"hello" Form.string;
            Form.button_no_value ~button_type:`Submit [pcdata "Submit"];
            ] in
        Lwt.return
            (html
            (head (title (pcdata "Main")) [])
            (body [Form.post_form step2_service step2_form ()]))
    and step2_handler () (n, s) =
        Lwt.return
            (html
            (head (title (pcdata "Step 2/2")) [])
            (body
                [
                p [pcdata ("N=" ^ string_of_int n)];
                p [pcdata ("S=" ^ s)];
                ])) in
    step1_handler () ()

let () =
    Eliom_registration.Html.register coucou_service coucou_handler
```

**Comment by darioteixeira** [comment]
Also, in previous versions one had to explicitly declare one wanted a POST co-service by calling `Eliom_registration.Html.register_post_coservice`.  I presume Eliom6's `Eliom_registration.Html.create` subsumes also that role, right?

**Comment by vasilisp** [comment]
That's indeed the way to do it. `` ~id:(Fallback ...)`` roughly corresponds to the old `*coservice` functions, and `~meth:(Post ...)` is obvious.

The redundancy is an unfortunate sacrifice towards the new uniform API, but of course we are open to suggestions on how this could be ameliorated :).

**Comment by darioteixeira** [comment]
> The redundancy is an unfortunate sacrifice towards the new uniform API, but of course we are open to suggestions on how this could be ameliorated :).

Most likely the problem comes from the various arguments (namely `meth` and `id`) not being entirely orthogonal. Anyway, in order to better understand the API, I'm writing an example that uses **all** Eliom6 service types.  The Eliom6 API is not yet documented, however, so I have some questions:

  * Type `id` has variants `Path`, `Fallback`, `Global`, and `External`.  If I understand these correctly, variant `Path` is used for "regular" visible services, and `External` for external services, right?
  * Is `Fallback` used exclusively for attached co-services? In previous versions of Eliom, the term "fallback" was used when declaring a POST service, to make sure it always had a GET service to fall back to.
  * Is `Global` used for non-attached services?

I think a matrix showing how the various combinations of `(meth, id, scope)` map into old Eliom5 service types would be useful.

**Comment by vasilisp** [comment]
> Type id has variants `Path`, `Fallback`, `Global`, and `External`. If I understand these correctly, variant `Path` is used for "regular" visible services, and `External` for external services, right?

Exactly.

> Is `Fallback` used exclusively for attached co-services? In previous versions of Eliom, the term "fallback" was used when declaring a POST service, to make sure it always had a GET service to fall back to.

Your understanding is right. Now it is possible to declare a POST service without necessarily having a GET service on the same path.

> Is `Global` used for non-attached services?

Exactly.

> I think a matrix showing how the various combinations of `(meth, id, scope)` map into old Eliom5 service types would be useful.

`scope` hasn't changed (not on purpose, at least). Indeed, we need such a matrix as part of a migration guide.

**Comment by darioteixeira** [comment]
Thanks for the prompt reply, @vasilisp!

> Your understanding is right. Now it is possible to declare a POST service without
> necessarily having a GET service on the same path.

Yes, I noticed that.  As for the terminology, calling it `Fallback` is potentially confusing for old Eliom users.  Though you can always fix this confusion by documenting the change clearly in big bold letters, it may be preferable to come with a new unambiguous name.  If indeed `Fallback` is now used exclusively for declaring attached co-services, and since the parameter of `Fallback` is the main service that this co-service is attached to, why not call it something like `Primary`, or `Main`, or `Super`, or something along these lines? (Or even `AttachedTo`, to make it extra clearer though more verbose...)

**Comment by vasilisp** [comment]
I intend to fix the name. I would personally prefer something like `Attached_to` to be absolutely clear, and to avoid camelcase :).

For the redundancy, I don't know what to do. I can think of technically possible solutions, like additional constructors in `meth` that only apply to coservices, but that's super ugly.

Suggestions?

**Comment by darioteixeira** [comment]
> I intend to fix the name. I would personally prefer something like Attached_to to be absolutely clear, and to avoid camelcase :).

Yeah, `Attached_to` would be clearest, though I reckon that even just `Attached` is clear enough and less ugly.

As for the redundancy, it is unfortunate, but not a deal breaker in the end.
