### ISSUE TITLE
what is `include module type of String_base` ?

### ISSUE THREAD

**Issue by pwbs** [ocsigen/eliom#314]
https://github.com/ocsigen/eliom/blob/master/src/lib/eliom_lib.client.mli#L50

**Comment by pwbs** [comment]
found it, it's in `ocsigenserver/src/baselib/ocsigen_lib_base.ml` ...

**Comment by pwbs** [comment]
`include module type of X` should be strictly forbidden when not mentioning where that `X` comes from if it's not local

**Comment by vasilisp** [comment]
Thanks, this should be fixed. See

http://ocsigen.org/eliom/dev/api/client/Eliom_lib
http://ocsigen.org/eliom/dev/api/server/Eliom_lib

**Comment by pwbs** [comment]
thank you @vasilisp !!
