### ISSUE TITLE
dead link in eliom documentation

### ISSUE THREAD

**Issue by Tormen** [ocsigen/eliom#317]
There is a dead link on this page: https://ocsigen.org/eliom/manual/server-outputs
The dead link is located under the header "Registering services that decide what they want to send": the  Eliom_registration.Any module

It links to: https://ocsigen.org/eliom/5.0/api/client/Eliom_registration.Any  But should link to: 
                 https://ocsigen.org/eliom/5.0/api/server/Eliom_registration.Any
(client -> server)

**Comment by vasilisp** [comment]
I fixed the issue in the development version, thanks!
