### ISSUE TITLE
misleading info in Eliom doc

### ISSUE THREAD

**Issue by Tormen** [ocsigen/eliom#318]
On this page: 
https://ocsigen.org/eliom/5.0/api/server/Eliom_registration.Any

It says following the signature of "val register_service":
    Same as Eliom_service.​Http.​service followed by Eliom_registration.​Any.​register.

Which to me is wrong & misleading as I tried to use "register_service" in the same way I used a the "register" function only to get a compiler complaint, because:

"register" returns "unit"
and
"register_service" returns an Eliom-Service

So to me this sentence should be:
    Same as Eliom_service.​Http.​service followed by Eliom_registration.​Any.​register, but returns the service!

And maybe give 1 sentence as to why it does... ?

**Comment by Tormen** [comment]
So I suppose "register" is mean to be called in an "init" function like let () = ...
And register_service is simply assigned to some value ?

**Comment by vasilisp** [comment]
You understand the difference well. In the `register` case you have a service already (so there is nothing to return), but in the `register_service` we also need to return the just-produced (and just-registered) service.

The service APIs have changed quite a lot in the upcoming version, and everything in the documentation needs to be updated accordingly. We need to take your remarks into account when we get to it :).

**Comment by vasilisp** [comment]
Fixed by 2dd12d39bc118fe611ced25af4ca57bef7793531 for the appropriate signatures (under `Eliom_registration_sigs`).
