### ISSUE TITLE
Support Format-based pretty-printer in Eliom

### ISSUE THREAD

**Issue by darioteixeira** [ocsigen/eliom#319]
Tyxml 4.0 introduced the new Format-based pretty-printing API (function `Html.pp` et al). Eliom's master still uses the old and less flexible `Eliom_content.Html.Printer` module, but there's no reason why at least `Eliom_content.Html.F` couldn't also use Tyxml's new pretty-printer.

**Comment by vasilisp** [comment]
PR #312 :). Misnamed because I was driven by deprecation warnings more than by new functionality, but that should do.

**Comment by Drup** [comment]
Note that you can't say "just for F" since everything can be nested (you can have a bit of R inside of F, and so on). Also, the datatype is the same. 

But yes, that should be doable.

**Comment by vasilisp** [comment]
Fixed by #312.
