### ISSUE TITLE
[Opam] Fix installability of eliom 5 with ocaml 4.03

### ISSUE THREAD

**Issue by Kakadu** [ocsigen/eliom#324]
At the moment we have some camlp4 related problem. Maybe fixing just opam recipe will be enough?
Anyway, @Drup , says that there is a fix in master but it should be considered for backporting.

````
➜  ~ opam install eliom.5.0.0
The following dependencies couldn't be met:
  - eliom -> camlp4 <= 4.02+6
Your request can't be satisfied:
  - camlp4<=4.02+6 is not available because your system doesn't comply with !preinstalled & ocaml-version >= "4.02" & ocaml-version < "4.03".

No solution found, exiting
➜  ~ evalopam 
4.03.0
1.2.2
➜  ~ opam pin
➜  ~ 
````

**Comment by vasilisp** [comment]
Fixing the OPAM constraints is not enough. We need a few patches (27c69ac5dfbc26744e304232bb8c0cf22d396082 and 291adaef9a9d3c04941a4af37dc895bb3c1602bd), but that's the easy part. The hard part is that Eliom 5.0.0 is tied to JSOO 2.7.0, which does not work with 4.03.0.

In summary, if you need OCaml 4.03.0, use Eliom master :).
