### ISSUE TITLE
Action broken in mobile apps :(

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#326]
When I call change_page to an action service with recent eliom,
I get (in the browser console):
[eliom] Async: ReferenceError: __eliom_request_data is not defined

On an older version, actions where redirecting to the browser :(

**Comment by balat** [comment]
@vasilisp can you reproduce?

**Comment by vasilisp** [comment]
@balat, I tried a few different setups and I can't reproduce. What kind of service is the action? Are you calling the action from a client-generated page?

I can't really see the connection. If `__eliom_request_data` is undefined, wouldn't the app be broken in many other ways?

**Comment by balat** [comment]
This happens only with a mobile app (not on a browser, even if the page is generated client-side) and *when the action is not registered client-side*.

The workaround is to register everything client-side.
We will wait for the new implementation of actions to confirm or close the bug.

**Comment by vasilisp** [comment]
The issue persists. I just hit it while trying to get something else working. In fact I can trigger it even without actions (with `App.send` inside an `Any` handler). I will look into it more carefully.
