### ISSUE TITLE
`Eliom_comet` and response delays

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#328]
Consider the following program:

``` ocaml
module Delay_app =
  Eliom_registration.App (
    struct
      let application_name = "delay"
      let global_data_path = None
    end)

let f =
  Eliom_client.server_function
    Deriving_Json.Json_unit.t
    (fun v -> Printf.printf "RPC\n%!"; Lwt.return ())

let e : unit Eliom_react.Down.t =
  Eliom_react.Down.of_react (fst (React.E.create ()))

let handler () () =
  ignore [%client (~%e : unit Eliom_react.Down.t) ];
  Lwt.return @@
  Eliom_tools.F.html ~title:"delay" ~css:[["css";"delay.css"]]
    Eliom_content.Html.(
      F.body [
        F.p ~a:[F.a_onclick [%client fun _ -> Lwt.async ~%f]]
          [F.pcdata "Do RPC"]
      ])

let _ =
  Delay_app.create
    ~id:   (Eliom_service.Path [])
    ~meth: (Eliom_service.Get Eliom_parameter.unit)
    handler
```

The program works fine for `<= 5` tabs, _i.e.,_ the server function `f` is called in a timely manner. Now, consider a sixth tab. We start observing delays in calling `f`. The delays are related to the periodicity of `Eliom_comet`. This could have very serious implications.

Credits to @canonici for observing a variant of this (with EBA).

**Comment by vouillon** [comment]
Web browsers typically open only up to 6 connections to a given web server.
A workaround would be to use a different host name for comet (and possibly several host names for comet services). This is what is done by Facebook, for instance.

**Comment by vasilisp** [comment]
Not really an Eliom issue. Closing.
