### ISSUE TITLE
Building with ppx syntax

### ISSUE THREAD

**Issue by Armael** [ocsigen/eliom#344]
Hi,

Following the instructions on http://ocsigen.org/eliom/5.0/manual/ppx-migration and http://ocsigen.org/eliom/dev/manual/workflow-compilation (section "ocamlbuild"), I tried to port my [eliom-skeleton](https://github.com/Armael/eliom-skeleton) repo to the new ppx syntax. I pushed the changes I made to the [ppxsyntax branch](https://github.com/Armael/eliom-skeleton/tree/ppxsyntax).

I thought I followed the documentation, but I can't manage to get the `ppxsyntax` branch to compile. Apparently it's still trying to use camlp4.

Any help welcome,
— Armael

**Comment by vasilisp** [comment]
Hi, the `eliom_ppx` flag is only available in master, not 5.0 .

**Comment by Armael** [comment]
Ah, I see. Is there a way of having a similar setup (ppx syntax, ocamlbuild using the ocamlbuild plugin) with eliom 5.0? Or do I have to switch to eliom master?

**Comment by vasilisp** [comment]
I don't know of an easy way. You could take the Ocamlbuild code from the Eliom repo (under `src/ocamlbuild`) and integrate it into your project.

However, I think it is a better use of your time to migrate to Eliom `master`, which will be released in the not-too-distant future.
