### ISSUE TITLE
Use PPX internally

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#348]
I think all the prerequisites are there: we have PPX extensions for JSOO and Lwt, we have `ppx_deriving_json`, and we have killed `pa_include`.

There are no backwards-compatibility issues. We have broken compatibility with OCaml 4.01 anyway, and we can still provide the Camlp4 extension for external code that still needs it.

Using PPX will possibly speed up compilation, we will be able to develop Eliom in saner language, and it will hopefully help @Drup :).

**Comment by vasilisp** [comment]
The branch `ppx-internally` seems to work. CC @Drup .

I did a pass through `camlp4-to-ppx`, fixed some Camlp4-isms, and made some changes for `ppx_deriving_json` (whose output is not identical to the Camlp4 version).

We also need a small fix in `ppx_deriving_json`: ocsigen/js_of_ocaml@0a7fea9724b5c4c74a30ab774d65c8d8a9cfea7e .

**Comment by Drup** [comment]
Hum, apparently we still have a necessary dependency to camlp4 for optcomp ... Can we get rid of that too and use cppo instead ? :]

**Comment by vasilisp** [comment]
Yes, I haven't dealt with the tools yet, just with the lib.
 
Sure, we will get rid of `optcomp` :).

**Comment by vasilisp** [comment]
Actually, `optcomp` had become useless when we dropped support for 4.01 and older. So I dropped it.

We can't yet make the dependency on Camlp4 optional because JSOO uses it.

**Comment by vasilisp** [comment]
On my laptop, compilation time goes from about 3.5 minutes to about 2 minutes (and we could probably do better with `ppx_driver` and less forking).

**Comment by vasilisp** [comment]
Fixed by #349 .
