### ISSUE TITLE
Remove reload actions 

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#355]
Reload actions cause trouble in the typing of services: without them, _registrable_ would be the negation of _external_.

At a conceptual level, I am not sure that reloading the current page can be meaningfully thought of as a service.

@balat, do you see some deep need for them? I seem to remember that you claimed we can remove them (under what conditions?).

CC @Drup

**Comment by Drup** [comment]
(Concretely, removing those means we can remove one type parameters in `id`)
