### ISSUE TITLE
Doc error in tuto

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/eliom#356]
In http://ocsigen.org/tuto/manual/tutowidgets , it's written:

you can write let%client , let%server or let%shared (default) to define values on client side, on server side, or on both sides.

I believe the default is server, not shared.

**Comment by vasilisp** [comment]
It was written in an unclear way.  It was talking about `[%%shared ...]`, inside which shared is the default. I hope it is a bit clearer now.
