### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/eliom#361]
http://ocsigen.org/eliom/1.3.4/manual/params

Path suffixes as parameters ¶

The code overflows from the gray boxes on my browser. 

http://ocsigen.org/eliom/1.3.4/manual/outputs

"Do not use with Eliom application: use Eliom_registration.​Ocaml instead."

There seems to be something missing here, it doesn't mean anything. It is explained better down the page with:
"For sending HTML to client side eliom application, Eliom_registration.​Ocaml is better suited." Although even after reading this, it's still very obscure to me when to use Flow5 and when to use Ocaml.

Registering services that decide what they want to send ¶

Very badly formatted code in the gray box.

**Comment by vasilisp** [comment]
You are looking at documentation for Eliom 1.3.4, which is very old :). There is a dropdown menu for choosing a version. These pages no longer exist.

**Comment by bruce-ricard** [comment]
Gosh, thanks. I have no idea how I ended on this version.

**Comment by vasilisp** [comment]
Actually, these pages still exist (with different names) and most of the issues persist, so we do need to take a look. Thanks!

**Comment by vasilisp** [comment]
Should be fixed.
