### ISSUE TITLE
crashing OS X Safari's engine

### ISSUE THREAD

**Issue by pwbs** [ocsigen/eliom#362]
Following discussion started at https://github.com/ocsigen/eliom/commit/7c199de220719fe9750d21502948e649cd5995e1

Summary: somewhere between https://github.com/ocsigen/eliom/commit/a1889d4696f3cf46a701b5f77d95b166d97cedeb  and https://github.com/ocsigen/eliom/commit/9ab810f4ab0e38968a5ca539f48d6e66d2e03e1b something (probably in the generated JS) broke Safari's engine (which triggers a `SIGSEGV`).

> Maybe the mere presence of lots of EBA code causes trouble. Does the `Eba_page.Make(Page_config)` in bar_page.eliom make a difference?

I'm having troubles understanding this question...

**Comment by vasilisp** [comment]
> I'm having troubles understanding this question... 

If you remove the functor invocation `Eba_page.Make(Page_config)` from the `bar_page.eliom` in the `bar.zip` you attached, does Safari still segfault?

**Comment by pwbs** [comment]
If I do that, it doesn't compile... `Error: Unbound module Bar_page.Opt`

**Comment by pwbs** [comment]
I'm now back to trying to solve this issue. Replacing the functor invocation by
```ocaml
(* include Os_page.Make(Page_config) *)

module Opt = struct
  let connected_page _ () () =  Lwt.return
      (html (head (title (pcdata "")) []) (body [pcdata "plop"]))

end
```
still makes Safari crash.
