### ISSUE TITLE
Ocsigen.org unavailable

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/eliom#366]
I can't browse ocsigen.org unless I use https. Feels like a bug.

**Comment by agarwal** [comment]
Both `http` and `https` work for me.

**Comment by bruce-ricard** [comment]
It now works for me too. But at the time I created the bug I couldn't
through http.

**Comment by vasilisp** [comment]
I don't know what happened (it may have been something beyond our control), but I guess we can close this now.
