### ISSUE TITLE
Eliom distillery corrupts binary files (URGENT for Eliom 6)

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#417]
It adds a newline at the end (and could possibly do other changes).
This breaks the fonts in Ocsigen Start, for the mobile app.

A solution could be to use a special suffix for binary files and just copy them without change.

**Comment by vasilisp** [comment]
OK, I will do this. What suffix would you prefer? Something like `.eliom_verbatim`? Or maybe an `.eliomverbatim` file listing them?

**Comment by balat** [comment]
Ok thank you!
The prefix you prefer. I like both of them.
