### ISSUE TITLE
eliompp doesn't work with PPX

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#423]
The ocsigen-start documentation doesn't show the contents of client-side modules. I think it boils down to `eliompp` (called by `eliomdoc`), which does not handle PPX at all. It finds no `{section{ }}` annotations, so it assumes everything is server code.

That's critical. We can't release `ocsigen-{toolkit,start}` with the documentation in that state.

For the documentation of Eliom itself, we don't use `eliomdoc` at all (but `ocamldoc` with the appropriate PPX). This has its own issues: comments that are for the wrong side, e.g., the last line in https://ocsigen.org/eliom/dev/api/client/Eliom_cscache . That needs to be fixed also.

**Comment by vasilisp** [comment]
Assuming we only need `.eliomi` files (which is not true in general, but will be OK for the upcoming releases), I can modify `eliompp` to recognize `[%%section.start]`.

Recognizing `[%%section ]` would be another story. We would need a `]` token, but that appears in many places unrelated to sections. `eliompp` is dump, it doesn't really parse OCaml, so we can't tell what the `]` is for.

**Comment by balat** [comment]
I agree this is critical.
Do we support `[%%section ]` in eliomi files?

**Comment by balat** [comment]
Ok I understood your comment. Ok indeed supporting eliomi files is probably enough for the release ...

**Comment by vasilisp** [comment]
>  Do we support [%%section ] in eliomi files?

Not yet, because it was not supported at all by OCaml `4.02.x` (which we still support). So we can forget about that for now.
