### ISSUE TITLE
eliom 5.0.0 opam package broken

### ISSUE THREAD

**Issue by xapantu** [ocsigen/eliom#430]
The package in opam, eliom 5.0.0 can not compile with js_of_ocaml 2.8.3. Downgrading js_of_ocaml to 2.7 fixes the issue.

**Comment by vasilisp** [comment]
See https://github.com/ocaml/opam-repository/issues/7919. It should be fixed, wait for the OPAM mirrors to sync.

**Comment by xapantu** [comment]
Thanks for the quick answer!
