### ISSUE TITLE
Release 6.0.1

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#441]
We will need a bugfix release soon. I will do it in about a week with whatever fixes we have accumulated by then.

We have already accumulated a few fixes, mostly counteracting my own carelessness before the 6.0 release :).

* Fix version in META file: cb01746a5dee01b2a7c3a3cdb6b99c8bf7bd8b97
* Remove redundant dependency on `calendar`: #439
* Fix client routing to `./`: #440 (impacts Ocsigen Start, see https://github.com/ocsigen/ocsigen-start/issues/342)

**Comment by dannywillems** [comment]
Two releases in one week! And a minor number for Eliom :).

**Comment by vasilisp** [comment]
Also #455 and #446. Maybe #444 also. From my POV, we can still call a release with all these 6.0.1; let's not be religious about what "new features" means, and let's not increase by 0.1 so fast :).

I could do that tomorrow.

**Comment by vasilisp** [comment]
Done. While I hesitated initially, we finally bumped the number up to 6.1 (SemVer).
