### ISSUE TITLE
Service Returns 404 Error

### ISSUE THREAD

**Issue by MiloDavis** [ocsigen/eliom#463]
I'm developing a program using Eliom, however the single service I have defined returns a 404 error.  The application can be found at https://github.com/MiloDavis/scouting/tree/bug-report.  I am using OCaml 4.0.3 and Eliom 6.1.0.  There should be no other dependencies, though the main application is meant to use Core and the development version of Base.

**Comment by MiloDavis** [comment]
I have also tried the same code with Eliom 6.0.0 and experienced the same issue.

**Comment by vasilisp** [comment]
In your [Makefile.options](https://github.com/MiloDavis/scouting/blob/97bfc317f6ee25bc242a427b4a54d1dbe909a45a/src/Makefile.options#L9), `SERVER_FILES` should include `*.eliom`, not `*.elioml`.

**Comment by MiloDavis** [comment]
Thank you.
