### ISSUE TITLE
Possibility for eliom functors?

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/eliom#466]
I have a service that depends on a module, and I'd like to have 2 services that use 2 different implementations of a module signature. Eliom won't let me create a functor in a .eliom file. Are you guys planning on implementing this in future versions?

What do you recommend to implement such a pattern without functors, duplicating my eliom code?

**Comment by Drup** [comment]
You can use functors inside eliom modules. What you can't do is use sections (`%client` and `%server`) inside functors.

**Comment by bruce-ricard** [comment]
OK yes sorry, that's what I meant. My service has server and client code, and depends on a module signature. And I wish I could have the whole thing functorial.

**Comment by Drup** [comment]
Ok, so yes, this is not possible for the moment (not even with the new WIP compiler). This is a difficult problem, we have some ideas, but I won't promise a solution in the short term.

The only alternative I can propose is to split your functor in two parts, the client part and the server part.

**Comment by bruce-ricard** [comment]
OK I thought about that. It defeats the purpose of being able to have server and client side code together though. Thanks for the quick answer!
