### ISSUE TITLE
Custom wrappers not working: hide Eliom_wrap.create_unwrapper or at least update the manual

### ISSUE THREAD

**Issue by mfp** [ocsigen/eliom#479]
The manual mentions in the "Custom unwrappers" section of the "Wrapping" chapter:

> Warning: The unwrapping mechanism has changed in Eliom 5.0. The information in this section is out-of-date.

Considering that unwrapping essentially works only within Eliom and cannot be used in regular client code, it'd be best to hide it altogether.

cf #232

**Comment by vasilisp** [comment]
Thanks!
