### ISSUE TITLE
Fix Fix hostname used by client app

### ISSUE THREAD

**Issue by pwbs** [ocsigen/eliom#495]
Sadly, https://github.com/ocsigen/eliom/pull/488 makes BeSport's app fully unusable: it makes the page displayed by the webview be `https?://hostname/index.html` instead of {`file:///blabla/index.html` and then `file:///blabla/eliom.html`}! (and of course, `https?://hostname/index.html` is a 404...)

**Comment by vasilisp** [comment]
We probably need a few `is_client_app` conditionals around the #488 code.

**Comment by balat** [comment]
Revert if the solution is not straightforward.

**Comment by vasilisp** [comment]
Reverting would be a very ugly thing to do, given the definitive issues addressed by #488.

Can you try b1ccffd092e2b578fc8a08379aa510aa7883fa3b ?

**Comment by pwbs** [comment]
b1ccffd092e2b578fc8a08379aa510aa7883fa3b seems to do the job!

**Comment by vasilisp** [comment]
OK, I took the liberty of committing it to `master`.
