### ISSUE TITLE
Documentation on generating external links with Eliom_service seems incorrect

### ISSUE THREAD

**Issue by shonfeder** [ocsigen/eliom#518]
Let me preface this with two caveats:

1. I'm not entirely sure this the right place to report the problem I've encountered.
2. I would be happy to help fix the problem reported.

To take action on either of these, I would need a pointer to the correct location.

---

While working through tutorial and documentation on Eliom, I have been struggling with how to create a simple link to an external URL. The main hurdles I was encountering seem to be the result of stale documentation.

I have been trying to work off of documentation available in the manual page on [creating links and forms](https://ocsigen.org/eliom/6.2/manual/server-links#links). However, my efforts were stymied by two apparent red herrings in the documentation.

The following example is given as (almost the sole) guidance for creating external links:

```ocaml
a
  (Eliom_service.Http.extern
     ~prefix:"http://fr.wikipedia.org"
     ~path:["wiki";""]
     ~meth:(Eliom_service.Get (suffix (all_suffix "suff")))
     ())
  [pcdata "OCaml on wikipedia"]
  ["OCaml"]
```

My efforts to follow this example have been stymied on two counts, both succinctly stated in the compilation errors:

1. `Error: Unbound module Eliom_service.Http`
2. `Error: Unbound value suffix`

Indeed, as soon as I removed reference to `suffix` and used `Eliom_service.extern` (without reference to non-existent `Http` submodule) everything compiled and functioned as expected! 

If I can get some guidance on where this `suffix` stuff is supposed to come from, and where I would submit a PR for the documentation, I would be happy to help fix this. If not, hopefully the reporting will help on its own!

---

The version of Eliom I'm using:

```
$ opam show eliom
             package: eliom
             version: 6.2.0
          repository: default
        upstream-url: https://github.com/ocsigen/eliom/archive/6.2.0.tar.gz
       upstream-kind: http
   upstream-checksum: 1e5461f3c99a5e53f92cb092f8b5fb8c
            homepage: http://ocsigen.org/eliom/
         bug-reports: https://github.com/ocsigen/eliom/issues/
            dev-repo: https://github.com/ocsigen/eliom.git
              author: dev@ocsigen.org
             license: LGPL-2.1 with OCaml linking exception
             depends: ocamlfind & deriving >= 0.6 & ppx_deriving & ppx_tools >= 0.99.3 & js_of_ocaml (>= 2.8.2 & < 3.0) & tyxml >= 4.0.0 & ocsigenserver >= 2.8 & ipaddr >= 2.1 & reactiveData >= 0.2.1 & (dbm | sqlite3) & base-bytes
   installed-version: 6.2.0 [4.04.2]
  available-versions: 2.2.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 4.0.0, 4.1.0, 4.2.0, 5.0.0, 6.0.0, 6.1.0, 6.2.0
         description: Client/server Web framework
```

**Comment by vasilisp** [comment]
Indeed, `Eliom_service.Http` no longer exists. We removed it in Eliom 6 but missed this part of the documentation.

`suffix` comes from `Eliom_parameter`.

You can do a PR against the Eliom repository. In particular, you would have to modify the file `doc/manual-wiki/server-links.wiki`. Thanks!

**Comment by shonfeder** [comment]
Thanks for the guidance, @vasilisp!
