### ISSUE TITLE
Using package ppx_deriving_lens breaks eliomc's perception of yojson/json ppx deriving syntax extensions

### ISSUE THREAD

**Issue by coventry** [ocsigen/eliom#563]
Given this in `test.eliom`:
```ocaml
type t = { i : int} [@@deriving yojson]
```
I get the following behavior:
```
/tmp$ eliomc -c -ppx test.eliom
/tmp$ eliomc -c -ppx -package ppx_deriving_lens test.eliom
File "test.eliom", line 1, characters 32-38:
Error: Cannot locate deriver yojson
```
Same thing *mutatis mutandis* with `json` instead of `yojson`.

**Comment by chrismamo1** [comment]
I seem to be able to get it to work by explicitly adding `ppx_deriving_yojson` on the command line, e.g

```ocaml
eliomc -c -ppx -package ppx_deriving_yojson -package lens.ppx_deriving test.eliom
```

As an aside, I found a few references on Google alluding to the existence of a package named as `ppx_deriving_lens`, but I think you meant to say `lens.ppx_deriving`.

**Comment by coventry** [comment]
This issue is probably out of date.
