### ISSUE TITLE
compatibility issues: tyxml, js_of_ocaml-tyxml, js_of_ocaml

### ISSUE THREAD

**Issue by jrochel** [ocsigen/eliom#580]
eliom doesn't compile with tyxml.4.3.0, js_of_ocaml.3.3, js_of_ocaml-tyxml.3.2.0, and various combinations thereof. In fact even if it compiles subsequent compilation of ocsigen-start fails. In any case, I'm going to work on this now. If anyone else is already working on this or wants to work on it, please get in contact with me.

**Comment by jrochel** [comment]
I'm tagging @Drup as he has put version constraints on the last release on the opam repository, so he's aware of the problem and might already be working on it...

**Comment by Drup** [comment]
I'm not. Go forth! :)

**Comment by jrochel** [comment]
Done. https://github.com/ocsigen/eliom/pull/581
