### ISSUE TITLE
Eliom does not compile on arch Armv7l anymore

### ISSUE THREAD

**Issue by Codeizer** [ocsigen/eliom#587]
File "src/lib/eliom_wrap.server.ml", line 132, characters 35-53:
Error: Integer literal exceeds the range of representable integers of type int
Command exited with code 2.

The last version that work was eliom.6.3.0 with ocaml 4.05.0

I am working on a raspberry pi

**Comment by vouillon** [comment]
Thanks a lot for you bug report! This is fixed by #588. We will make a release with this fix shortly.
