### ISSUE TITLE
camlp4 dependency in META (eliom.syntax.predef)

### ISSUE THREAD

**Issue by jaapb** [ocsigen/eliom#594]
When I try to compile ocsigen-start 1.5.0 from source with eliom 6.5.0, I get the following error:

eliomdep -server -package pgocaml -package pgocaml.syntax -package macaque.syntax -package calendar -package safepass -package resource-pooling -eliom-inc src/ src/os_core_db.ml > _deps/src/os_core_db.ml.server
Fatal error: exception Fl_package_base.No_such_package("js_of_ocaml-camlp4", "required by `eliom.syntax.predef'")
Makefile:192: .depend: No such file or directory

Given that camlp4 support has now been removed from js_of_ocaml, shouldn't this dependency be removed from eliom as well?

**Comment by domq** [comment]
Having the same issue today; just running

 ```
eliomdep -server  example.eliom
```

in a fresh checkout of `git@github.com:db0company/Ocsigen-Quick-Howto.git`, gives me the error. Everything is up-to-date re:  `opam` AFAICT.

**Comment by balat** [comment]
Closing this as outdated.
We don't use camlp4 anymore.
