### ISSUE TITLE
Fails to compile with Ocaml 4.06.0, js_of_ocaml 3.4.0, opam 2.1.0~beta

### ISSUE THREAD

**Issue by pat227** [ocsigen/eliom#607]
Ocaml 4.06.0
Eliom 6.3.0
Lwt 3.0.0
Lwt_log 1.0.0
Lwt_ppx 1.2.2
Fails to compile due to a dependency mismatch of some kind.
Compilation with opam v2.1.0~beta fails. 

Compilation from source (checking out eliom tag 6.3.0) fails because js_of_ocaml-lwt.logger is not found. Removing js_of_ocaml-lwt.logger from pkg/META and src/_tags may or may not fix or merely sidestep the issue, but it does allow compilation from source to proceed further until: 
1) lwt_ppx cannot be found, easily resolved by installation with opam, so this dependency is not being properly noted;
2) module lwt_log_js is not found, required in eliom_lib.client.mli. 
Looking at the source code for js_of_ocaml it appears lwt_log_js was removed, then the removal was reverted, and finally removed again on 19 Jan 2019, which is part of release 3.4, so perhaps Eliom 6.3.0 should rely on js_of_ocaml 3.3.0. Unfortunately, downgrading to js_of_ocaml 3.3.0 didn't resolve this issue.  

At this point I know I'm over my head...can anyone help?

**Comment by balat** [comment]
Closing this as outdated.
Feel free to create a new ticket if there are other installation problems.
