### ISSUE TITLE
[ocsigen.org] link to cheatsheet is dead

### ISSUE THREAD

**Issue by RuyBlast** [ocsigen/eliom#620]
Hi !
At url http://ocsigen.org/tuto/6.4/manual/interaction , an internal link towards `http://ocsigen.org/overview/cheatsheet` (text: "the cheat-sheet") is broken.
Best regards

**Comment by balat** [comment]
Unfortunately, the cheatsheet was very outdated.
But a brand new page has been added in the tutorial (dev version only for now) that will fill the same purpose.
https://ocsigen.org/tuto/dev/manual/basics
