### ISSUE TITLE
ocsigen.org documentation dead link

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/eliom#645]
Reproduction steps:

1. Navigate to https://ocsigen.org/eliom/5.0/api/server/Eliom_service.Http (notice it's the documentation for version 5)
1. Click on the Version dropdown and select version 6.6 (as of today).
1. Observe the 404

I was trying to see what the v6 way of doing that is, and it's not that easy.

**Comment by balat** [comment]
We decided to remove the documentation for old versions, as it is too difficult to maintain many versions.
Do not hesitate to contact us via https://discuss.ocaml.org if you have precise questions.
