### ISSUE TITLE
server_function regression?

### ISSUE THREAD

**Issue by bruce-ricard** [ocsigen/eliom#648]
Hello. I have this code:

```
type t = unit -> [ `A ] Lwt.t
let f = function () -> Lwt.return `A
let%client ff = ~%(server_function [%derive.json: unit] f)
```

Which used to work with Eliom 5, but with Eliom 6 returns the error
> Error: The type of this expression [...] contains type variables that cannot be generalized

We can fix it by coercing the type of `f` not to be open:
```
type t = unit -> [ `A ] Lwt.t
let f : t = function () -> Lwt.return `A
let%client ff = ~%(server_function [%derive.json: unit] f)
```

and it works.

**Comment by vouillon** [comment]
This is a change in OCaml 4.11. There is not much we can do about that.
