### ISSUE TITLE
Cannot build reactive application from tutorial

### ISSUE THREAD

**Issue by dboris** [ocsigen/eliom#652]
Following https://ocsigen.org/tuto/6.4/manual/tutoreact, I get a build error:
```
...
js_of_eliom -w +A-4-7-9-37-38-39-41-42-44-45-48 -jsopt +base/runtime.js -ppx -ppx "ocsigen-i18n-rewriter Tutoreact_i18n" -c -package lwt_ppx -package js_of_ocaml-ppx -package js_of_ocaml-ppx_deriving_json -package ppx_deriving.std -package ocsigen-start.client -package base -g tutoreact_messages.eliom
File "tutoreact_messages.eliom", line 52, characters 3-18:
Error: Unbound module Forum_notif
make: *** [_client/tutoreact_messages.cmo] Error 2
```

The error message suggests that module Forum_notif is being accessed on the client. I don't see any reference to it in the client slice, see:
https://github.com/dboris/eliom-tutoreact/blob/main/tutoreact_messages.eliom

The following repo can be used to reproduce the error:
https://github.com/dboris/eliom-tutoreact

**Comment by dboris** [comment]
I found a fix for the build error. The type for the client notification react event must be specified explicitly:
```
  ignore [%client
    (ignore
       (React.E.map (handle_notif_message_list ~%rmessages)
          ~%(Forum_notif.client_ev () : (unit * int) Eliom_react.Down.t))
     : unit)
  ];
```

I'll leave this issue open as a reminder that the tutorial needs updating.

**Comment by balat** [comment]
Thank you. Now fixed in https://github.com/ocsigen/tuto/commit/55c6241f0ded5c1a5e120eb94d60e664f53ad43f
