### ISSUE TITLE
Broken links on database usage

### ISSUE THREAD

**Issue by jteg68** [ocsigen/eliom#654]
https://ocsigen.org/tuto/dev/manual/how-to-use-a-database-with-eliom
The link to Macaque is https://ocsigen.org/macaque/index.html but maybe instead it should be https://github.com/ocsigen/macaque?

The link to pgocaml is https://download.ocamlcore.org/pgocaml/ but maybe is should instead be https://github.com/darioteixeira/pgocaml ? 

A couple of nice examples using postgresql with eliom would be nice as well.

Thanks,
Jörgen

**Comment by balat** [comment]
I'll remove this tutorial. It is outdated and not very useful.
