### ISSUE TITLE
Typos in the documentation

### ISSUE THREAD

**Issue by FardaleM** [ocsigen/eliom#679]
- [`Eliom_common.session`](https://github.com/ocsigen/eliom/blob/50e207e76cc09d0f0491be6b4eab9c14f600a77f/src/lib/eliom_state.server.mli#L39) does not seems to exist.
 -  [This](https://github.com/ocsigen/eliom/blob/50e207e76cc09d0f0491be6b4eab9c14f600a77f/src/lib/eliom_state.server.mli#L44) sentence seems not to be finished.
 - [`Eliom_reference.reset`](https://github.com/ocsigen/eliom/blob/50e207e76cc09d0f0491be6b4eab9c14f600a77f/src/lib/eliom_reference.server.mli#L93) does not seems to exists.

**Comment by balat** [comment]
Thanks! Fixed in dev branch.
