### ISSUE TITLE
Error: Unbound value

### ISSUE THREAD

**Issue by bguil** [ocsigen/eliom#695]
With the following code in file `test.eliom`:

```ocaml
let _ = Eliom_request_info.get_original_filename
```
The command `eliomc -ppx -infer test.eliom` works nicely with eliom 7.0.0 but fails with eliom 8.4.8

## eliom.7.0.0

* `opam list | grep eliom`
```
eliom                         7.0.0        Client/server Web framework
```

* `eliomc -ppx -infer test.eliom`

```
```

## eliom.8.4.8
* `opam list | grep eliom`
```
eliom                         8.4.8        Client/server Web framework
```

* `eliomc -ppx -infer test.eliom`

```
File "test.eliom", line 1, characters 8-48:
1 | let _ = Eliom_request_info.get_original_filename
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Eliom_request_info.get_original_filename
```

NB: I've observed the same problem on two different installation: Ocaml version 4.08.1 on Linux and Ocaml version 4.11.1 on MacOSX.

**Comment by bguil** [comment]
Just a ping on this uncommented issue. Any news about it?

**Comment by balat** [comment]
Indeed the function disappeared during the switch to cohttp.
By mistake I suppose or is there a reason @vasilisp ?
The information seems to be easily available https://github.com/ocsigen/ocsigenserver/blob/master/src/server/ocsigen_extensions.mli#L37
I suggest we put back the missing functions ...

**Comment by balat** [comment]
https://github.com/ocsigen/eliom/pull/715/files

**Comment by balat** [comment]
Merged
