### ISSUE TITLE
Typing error on Eliom >= 8.9.0

### ISSUE THREAD

**Issue by ghuysmans** [ocsigen/eliom#730]
Hi,

I can't compile a [test program with a simple server-generated button](https://github.com/ghuysmans/eliom-test/blob/simple_client/test.eliom). I've reduced it to a [simpler program](https://github.com/ghuysmans/eliom-test/blob/simple_client/mini.eliom) and tested different versions of Eliom, first locally then [on GitHub Actions](https://github.com/ghuysmans/eliom-test/runs/4419353689?check_suite_focus=true).

Starting from Eliom 8.9.0, it complains about a `'a Eliom_client_value.t option`:
```
$ eliomc -ppx -infer mini.eliom
File "mini.eliom", line 7, characters 25-46:
7 |     button ~a:[a_onclick [%client fun _ -> ()]] [txt "Click me!"];
                             ^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type 'a Eliom_client_value.t option
       but an expression was expected of type unit -> 'b
       Hint: Did you forget to wrap the expression using `fun () ->'?
Error: Process completed with exit code 2.
```

Have I done something wrong?

Thanks!

**Comment by vouillon** [comment]
Thanks for your detailed bug report!

The issue is that `Eliom_lib` provides a non-standard definition of `Option.get`, of type `(unit -> 'a) -> 'a t -> 'a` when the `-infer` option expects `'a option -> 'a`.

I need to make the PPX syntax extension more robust. But, in the meantime, you could avoid opening module `Eliom_lib`.

**Comment by ghuysmans** [comment]
Alright... [I couldn't reproduce it without opening Eliom_lib](https://github.com/ghuysmans/eliom-test/commit/263c9c790aeb38903466847d788f698c05593e14), but I didn't expect the PPX to be the culprit!
Thanks!
