### ISSUE TITLE
Error when running ocsigenserver: The module `B' is not yet initialized

### ISSUE THREAD

**Issue by bguil** [ocsigen/eliom#775]
With Ocaml 5.1.0 and eliom 10.1.2 installed on MacOSX, I have a strange bug which seems to be linked to the names of the files:

Step to reproduce:

 - `eliom-distillery -name test_eliom`
 - in `test_eliom` directory `make test.opt` works as expected
 - add a new file `b.eliom` with one line `module M = Map.Make (String)`
 - add a new file `a.eliom` with one line `let _ = B.M.empty`
 - then `make test.opt` produces the error: 
 ```
ocsigenserver.opt: main: Fatal - Error in configuration file: Error while parsing configuration file: Eliom: while loading local/lib/test_eliom/test_eliom.cmxs: error while linking [...]/test_eliom/local/lib/test_eliom/test_eliom.cmxs.
ocsigenserver.opt: main: The module `B' is not yet initialized
```

**NOTE**: if you rename `a.eliom` into `c.eliom`, the error disappears!

Is seems that the problem is linked to the names of the modules: 
 - `a.eliom` depends on `b.eliom` 
 - `a.eliom` is _before_ `b.eliom` following alphabetical order

Note also that I do not have the error with OCaml 4.14.1 and eliom 10.1.2

**Comment by bguil** [comment]
Thanks for the fix. I've updated the Makefile following your PR, it's fixed.

I'd also like to take this opportunity to also mention a problem that sometimes occurs. When a module name is changed, sometimes doing `make clean && make` is not enough and I have to run `rm -rf _deps` to come to a running version.
Perhaps the Makefile can be improved to avoid this?

**Comment by balat** [comment]
Thank you for the bug report. We will release a new version version soon.
It will also contain a new template with dune-based build system.
I recommend to switch to this one.
